// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

using System;

namespace DominoTrainGame;

public partial class Account
{
    public int AccountId { get; set; }
    public string Biography { get; set; }
    public string PreferredLanguage { get; set; }
    public Nullable<System.DateTime> CreatedAt { get; set; }
    public System.DateTime LastSeenAt { get; set; }
    public int PlayerId { get; set; }

    public virtual Player Player { get; set; }
}
