// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

using System;

namespace DominoTrainGame;

public partial class Ban
{
    public int BanId { get; set; }
    public int PlayerId { get; set; }
    public string Reason { get; set; }
    public string BanType { get; set; }
    public System.DateTime StartedAt { get; set; }
    public Nullable<System.DateTime> ExpiresAt { get; set; }
    public virtual Player Player { get; set; }
}
