//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public int BanId { get; set; }
        public int PlayerId { get; set; }
        public string Reason { get; set; }
        public string BanType { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
