// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame;

public partial class FriendshipRequest
{
    public int FriendshipRequestId { get; set; }
    public int RequesterPlayerId { get; set; }
    public int AddresseePlayerId { get; set; }
    public int StatusId { get; set; }
    public System.DateTime RequestedAt { get; set; }
    public virtual Player AddresseePlayer { get; set; }
    public virtual Player RequesterPlayer { get; set; }
    public virtual StatusFriendshipRequest StatusFriendshipRequest { get; set; }
}
