//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LobbyPlayer
    {
        public int PlayerId { get; set; }
        public int LobbyId { get; set; }
        public byte IsReady { get; set; }
    
        public virtual Lobby Lobby { get; set; }
        public virtual Player Player { get; set; }
    }
}
