// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame;

public partial class LobbyPlayer
{
    public int PlayerId { get; set; }
    public int LobbyId { get; set; }
    public byte IsReady { get; set; }
    public virtual Lobby Lobby { get; set; }
    public virtual Player Player { get; set; }
}
