// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame;

public partial class MatchResult
{
    public int PlayerId { get; set; }
    public int MatchId { get; set; }
    public int FinalRank { get; set; }
    public int TotalScore { get; set; }
    public virtual Match Match { get; set; }
    public virtual Player Player { get; set; }
}
