// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

using System.Collections.Generic;

namespace DominoTrainGame;

public partial class Match
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "Microsoft.Usage",
        "CA2214:DoNotCallOverridableMethodsInConstructors"
    )]
    public Match()
    {
        this.MatchResults = new HashSet<MatchResult>();
    }

    public int MatchId { get; set; }
    public int LobbyId { get; set; }
    public string Status { get; set; }

    public virtual Lobby Lobby { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MatchResult> MatchResults { get; set; }
}
