// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame;

public partial class Report
{
    public int ReportId { get; set; }
    public int PlayerId { get; set; }
    public string Reason { get; set; }

    public virtual Player Player { get; set; }
}
