// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

using System.Collections.Generic;

namespace DominoTrainGame;

public partial class StatusFriendshipRequest
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "Microsoft.Usage",
        "CA2214:DoNotCallOverridableMethodsInConstructors"
    )]
    public StatusFriendshipRequest()
    {
        this.FriendshipRequests = new HashSet<FriendshipRequest>();
    }

    public int StatusId { get; set; }
    public string Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FriendshipRequest> FriendshipRequests { get; set; }
}
