//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominoTrainGame.Resources.Localization.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / SEGURIDAD.
        /// </summary>
        public static string AccountSecuritySectionLabel {
            get {
                return ResourceManager.GetString("AccountSecuritySectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta?.
        /// </summary>
        public static string AlreadyHaveAccountLabel {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / AUDIO.
        /// </summary>
        public static string AudioSectionLabel {
            get {
                return ResourceManager.GetString("AudioSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLVER.
        /// </summary>
        public static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMIGOS.
        /// </summary>
        public static string ButtonFriends {
            get {
                return ResourceManager.GetString("ButtonFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGAR.
        /// </summary>
        public static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELAR.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelEditAccessibleName {
            get {
                return ResourceManager.GetString("CancelEditAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Cambiar contraseña.
        /// </summary>
        public static string ChangePasswordWindowTitle {
            get {
                return ResourceManager.GetString("ChangePasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMAR NUEVA CONTRASEÑA.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al registro.
        /// </summary>
        public static string CreateAccountAccessibleName {
            get {
                return ResourceManager.GetString("CreateAccountAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string CreateAccountLinkLabel {
            get {
                return ResourceManager.GetString("CreateAccountLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/ CREDENCIALES.
        /// </summary>
        public static string CredentialSectionLabel {
            get {
                return ResourceManager.GetString("CredentialSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA ACTUAL.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña actual..
        /// </summary>
        public static string CurrentPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entiendo que esta acción no se puede deshacer..
        /// </summary>
        public static string DeleteAccountConfirmationLabel {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma que deseas eliminar tu cuenta..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña para confirmar tu identidad..
        /// </summary>
        public static string DeleteAccountPasswordHint {
            get {
                return ResourceManager.GetString("DeleteAccountPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR CUENTA.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez eliminada, no podrás recuperar tu cuenta..
        /// </summary>
        public static string DeleteAccountWarningDescription {
            get {
                return ResourceManager.GetString("DeleteAccountWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCIÓN PERMANENTE.
        /// </summary>
        public static string DeleteAccountWarningTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Eliminar cuenta.
        /// </summary>
        public static string DeleteAccountWindowTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR.
        /// </summary>
        public static string EditButtonLabel {
            get {
                return ResourceManager.GetString("EditButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de correo electrónico.
        /// </summary>
        public static string EmailAccessibleName {
            get {
                return ResourceManager.GetString("EmailAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREO ELECTRÓNICO.
        /// </summary>
        public static string EmailAdressLabel {
            get {
                return ResourceManager.GetString("EmailAdressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Los campos obligatorios no pueden estar vacíos.
        /// </summary>
        public static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés / English.
        /// </summary>
        public static string EnglishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("EnglishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string EnglishLanguageCode {
            get {
                return ResourceManager.GetString("EnglishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string EnglishLanguageDescription {
            get {
                return ResourceManager.GetString("EnglishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string ForgotPasswordAccessibleName {
            get {
                return ResourceManager.GetString("ForgotPasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTA DE AMIGOS.
        /// </summary>
        public static string FriendListWindowTitle {
            get {
                return ResourceManager.GetString("FriendListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINO TRAIN.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión.
        /// </summary>
        public static string GoToLoginLabel {
            get {
                return ResourceManager.GetString("GoToLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        public static string GuestButtonAccessibleName {
            get {
                return ResourceManager.GetString("GuestButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGAR COMO INVITADO.
        /// </summary>
        public static string GuestButtonLabel {
            get {
                return ResourceManager.GetString("GuestButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La contraseña debe tener al menos {0} caracteres.
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚNETE A LA MESA.
        /// </summary>
        public static string JoinTableTitle {
            get {
                return ResourceManager.GetString("JoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 / IDIOMA.
        /// </summary>
        public static string LanguageSectionLabel {
            get {
                return ResourceManager.GetString("LanguageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LoginButtonAccessibleName {
            get {
                return ResourceManager.GetString("LoginButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAR SESIÓN.
        /// </summary>
        public static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de correo electrónico o usuario.
        /// </summary>
        public static string LoginIdentifierAccessibleName {
            get {
                return ResourceManager.GetString("LoginIdentifierAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREO ELECTRÓNICO O USUARIO.
        /// </summary>
        public static string LoginIdentifierLabel {
            get {
                return ResourceManager.GetString("LoginIdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIO DE SESION.
        /// </summary>
        public static string LoginSectionTitle {
            get {
                return ResourceManager.GetString("LoginSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión para continuar tu partida.
        /// </summary>
        public static string LoginSidebarDescription {
            get {
                return ResourceManager.GetString("LoginSidebarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIENVENIDO DE VUELTA.
        /// </summary>
        public static string LoginSiderBarLabel {
            get {
                return ResourceManager.GetString("LoginSiderBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren de domino - Inicio de sesión.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÚSICA.
        /// </summary>
        public static string MusicVolumeLabel {
            get {
                return ResourceManager.GetString("MusicVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ NUEVO PASAJERO.
        /// </summary>
        public static string NewPassagerSubtitule {
            get {
                return ResourceManager.GetString("NewPassagerSubtitule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una contraseña diferente a la actual y confírmala..
        /// </summary>
        public static string NewPasswordHint {
            get {
                return ResourceManager.GetString("NewPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA CONTRASEÑA.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        public static string NoAccountLabel {
            get {
                return ResourceManager.GetString("NoAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL.
        /// </summary>
        public static string OpenProfileButtonLabel {
            get {
                return ResourceManager.GetString("OpenProfileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string OpenSettingsButtonLabel {
            get {
                return ResourceManager.GetString("OpenSettingsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de contraseña.
        /// </summary>
        public static string PasswordAccessibleName {
            get {
                return ResourceManager.GetString("PasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compartas tu contraseña con otros jugadores..
        /// </summary>
        public static string PasswordPrivacyNote {
            get {
                return ResourceManager.GetString("PasswordPrivacyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu próximo viaje comienza con una cuenta segura..
        /// </summary>
        public static string ProtectAccountDescription {
            get {
                return ResourceManager.GetString("ProtectAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma asiento y regístrate para comenzar tu partida.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRO.
        /// </summary>
        public static string RegisterSectionTitle {
            get {
                return ResourceManager.GetString("RegisterSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro completado correctamente.
        /// </summary>
        public static string RegisterSucessMessage {
            get {
                return ResourceManager.GetString("RegisterSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string RegisterTittle {
            get {
                return ResourceManager.GetString("RegisterTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUARDAR.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveProfileAccessibleName {
            get {
                return ResourceManager.GetString("SaveProfileAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Configuración.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRARSE.
        /// </summary>
        public static string SignUpBottonLabel {
            get {
                return ResourceManager.GetString("SignUpBottonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar nueva cuenta.
        /// </summary>
        public static string SignUpButtonAccesibleName {
            get {
                return ResourceManager.GetString("SignUpButtonAccesibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren de domino - Inicio de sesión.
        /// </summary>
        public static string SignUpWindowTitle {
            get {
                return ResourceManager.GetString("SignUpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFECTOS DE SONIDO.
        /// </summary>
        public static string SoundEffectsVolumeLabel {
            get {
                return ResourceManager.GetString("SoundEffectsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string SpanishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("SpanishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        public static string SpanishLanguageCode {
            get {
                return ResourceManager.GetString("SpanishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SpanishLanguageDescription {
            get {
                return ResourceManager.GetString("SpanishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string SpanishLanguageName {
            get {
                return ResourceManager.GetString("SpanishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALIZAR.
        /// </summary>
        public static string UpdatePasswordButtonLabel {
            get {
                return ResourceManager.GetString("UpdatePasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de nombre de usuario.
        /// </summary>
        public static string UsernameAccessibleName {
            get {
                return ResourceManager.GetString("UsernameAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE DE USUARIO.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}%.
        /// </summary>
        public static string VolumePercentageFormat {
            get {
                return ResourceManager.GetString("VolumePercentageFormat", resourceCulture);
            }
        }
    }
}
