//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominoTrainGame.Resources.Localization.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01 / SEGURIDAD.
        /// </summary>
        public static string AccountSecuritySectionLabel {
            get {
                return ResourceManager.GetString("AccountSecuritySectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        public static string AlreadyHaveAccountLabel {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01 / AUDIO.
        /// </summary>
        public static string AudioSectionLabel {
            get {
                return ResourceManager.GetString("AudioSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER.
        /// </summary>
        public static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a inicio de sesión.
        /// </summary>
        public static string BackToLoginLabel {
            get {
                return ResourceManager.GetString("BackToLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        public static string ButtonResendCode {
            get {
                return ResourceManager.GetString("ButtonResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Verificar.
        /// </summary>
        public static string ButtonVerify {
            get {
                return ResourceManager.GetString("ButtonVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelEditAccessibleName {
            get {
                return ResourceManager.GetString("CancelEditAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino Train · Cambiar contraseña.
        /// </summary>
        public static string ChangePasswordWindowTitle {
            get {
                return ResourceManager.GetString("ChangePasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIRMAR NUEVA CONTRASEÑA.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al registro.
        /// </summary>
        public static string CreateAccountAccessibleName {
            get {
                return ResourceManager.GetString("CreateAccountAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string CreateAccountLinkLabel {
            get {
                return ResourceManager.GetString("CreateAccountLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01/ CREDENCIALES.
        /// </summary>
        public static string CredentialSectionLabel {
            get {
                return ResourceManager.GetString("CredentialSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA ACTUAL.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu contraseña actual..
        /// </summary>
        public static string CurrentPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entiendo que esta acción no se puede deshacer..
        /// </summary>
        public static string DeleteAccountConfirmationLabel {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma que deseas eliminar tu cuenta..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu contraseña para confirmar tu identidad..
        /// </summary>
        public static string DeleteAccountPasswordHint {
            get {
                return ResourceManager.GetString("DeleteAccountPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR CUENTA.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una vez eliminada, no podrás recuperar tu cuenta..
        /// </summary>
        public static string DeleteAccountWarningDescription {
            get {
                return ResourceManager.GetString("DeleteAccountWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCIÓN PERMANENTE.
        /// </summary>
        public static string DeleteAccountWarningTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino Train · Eliminar cuenta.
        /// </summary>
        public static string DeleteAccountWindowTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR.
        /// </summary>
        public static string EditButtonLabel {
            get {
                return ResourceManager.GetString("EditButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de correo electrónico.
        /// </summary>
        public static string EmailAccessibleName {
            get {
                return ResourceManager.GetString("EmailAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO ELECTRÓNICO.
        /// </summary>
        public static string EmailAdressLabel {
            get {
                return ResourceManager.GetString("EmailAdressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: Los campos obligatorios no pueden estar vacíos.
        /// </summary>
        public static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés / English.
        /// </summary>
        public static string EnglishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("EnglishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EN.
        /// </summary>
        public static string EnglishLanguageCode {
            get {
                return ResourceManager.GetString("EnglishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string EnglishLanguageDescription {
            get {
                return ResourceManager.GetString("EnglishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string ForgotPasswordAccessibleName {
            get {
                return ResourceManager.GetString("ForgotPasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LISTA DE AMIGOS.
        /// </summary>
        public static string FriendListWindowTitle {
            get {
                return ResourceManager.GetString("FriendListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOMINO TRAIN.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión.
        /// </summary>
        public static string GoToLoginLabel {
            get {
                return ResourceManager.GetString("GoToLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string GuestButtonAccessibleName {
            get {
                return ResourceManager.GetString("GuestButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGAR COMO INVITADO.
        /// </summary>
        public static string GuestButtonLabel {
            get {
                return ResourceManager.GetString("GuestButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: La contraseña debe tener al menos {0} caracteres.
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ÚNETE A LA MESA.
        /// </summary>
        public static string JoinTableTitle {
            get {
                return ResourceManager.GetString("JoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 02 / IDIOMA.
        /// </summary>
        public static string LanguageSectionLabel {
            get {
                return ResourceManager.GetString("LanguageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LoginButtonAccessibleName {
            get {
                return ResourceManager.GetString("LoginButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR SESIÓN.
        /// </summary>
        public static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de correo electrónico o usuario.
        /// </summary>
        public static string LoginIdentifierAccessibleName {
            get {
                return ResourceManager.GetString("LoginIdentifierAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO ELECTRÓNICO O USUARIO.
        /// </summary>
        public static string LoginIdentifierLabel {
            get {
                return ResourceManager.GetString("LoginIdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIO DE SESION.
        /// </summary>
        public static string LoginSectionTitle {
            get {
                return ResourceManager.GetString("LoginSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia sesión para continuar tu partida.
        /// </summary>
        public static string LoginSidebarDescription {
            get {
                return ResourceManager.GetString("LoginSidebarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BIENVENIDO DE VUELTA.
        /// </summary>
        public static string LoginSiderBarLabel {
            get {
                return ResourceManager.GetString("LoginSiderBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tren de domino - Inicio de sesión.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino Train.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MÚSICA.
        /// </summary>
        public static string MusicVolumeLabel {
            get {
                return ResourceManager.GetString("MusicVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ■ NUEVO PASAJERO.
        /// </summary>
        public static string NewPassagerSubtitule {
            get {
                return ResourceManager.GetString("NewPassagerSubtitule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige una contraseña diferente a la actual y confírmala..
        /// </summary>
        public static string NewPasswordHint {
            get {
                return ResourceManager.GetString("NewPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVA CONTRASEÑA.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string NoAccountLabel {
            get {
                return ResourceManager.GetString("NoAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMIGOS.
        /// </summary>
        public static string OpenFriendsListLabel {
            get {
                return ResourceManager.GetString("OpenFriendsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERFIL.
        /// </summary>
        public static string OpenProfileButtonLabel {
            get {
                return ResourceManager.GetString("OpenProfileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        public static string OpenSettingsButtonLabel {
            get {
                return ResourceManager.GetString("OpenSettingsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de contraseña.
        /// </summary>
        public static string PasswordAccessibleName {
            get {
                return ResourceManager.GetString("PasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No compartas tu contraseña con otros jugadores..
        /// </summary>
        public static string PasswordPrivacyNote {
            get {
                return ResourceManager.GetString("PasswordPrivacyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu próximo viaje comienza con una cuenta segura..
        /// </summary>
        public static string ProtectAccountDescription {
            get {
                return ResourceManager.GetString("ProtectAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toma asiento y regístrate para comenzar tu partida.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRO.
        /// </summary>
        public static string RegisterSectionTitle {
            get {
                return ResourceManager.GetString("RegisterSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completado correctamente.
        /// </summary>
        public static string RegisterSucessMessage {
            get {
                return ResourceManager.GetString("RegisterSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string RegisterTittle {
            get {
                return ResourceManager.GetString("RegisterTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string SaveProfileAccessibleName {
            get {
                return ResourceManager.GetString("SaveProfileAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domino Train · Configuración.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRARSE.
        /// </summary>
        public static string SignUpBottonLabel {
            get {
                return ResourceManager.GetString("SignUpBottonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar nueva cuenta.
        /// </summary>
        public static string SignUpButtonAccesibleName {
            get {
                return ResourceManager.GetString("SignUpButtonAccesibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tren de domino - Inicio de sesión.
        /// </summary>
        public static string SignUpWindowTitle {
            get {
                return ResourceManager.GetString("SignUpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EFECTOS DE SONIDO.
        /// </summary>
        public static string SoundEffectsVolumeLabel {
            get {
                return ResourceManager.GetString("SoundEffectsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string SpanishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("SpanishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ES.
        /// </summary>
        public static string SpanishLanguageCode {
            get {
                return ResourceManager.GetString("SpanishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string SpanishLanguageDescription {
            get {
                return ResourceManager.GetString("SpanishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string SpanishLanguageName {
            get {
                return ResourceManager.GetString("SpanishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string TabFriends {
            get {
                return ResourceManager.GetString("TabFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string TabRequests {
            get {
                return ResourceManager.GetString("TabRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTUALIZAR.
        /// </summary>
        public static string UpdatePasswordButtonLabel {
            get {
                return ResourceManager.GetString("UpdatePasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo de nombre de usuario.
        /// </summary>
        public static string UsernameAccessibleName {
            get {
                return ResourceManager.GetString("UsernameAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DE USUARIO.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        public static string VerificationCodeAccessibleName {
            get {
                return ResourceManager.GetString("VerificationCodeAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No recibiste el correo?.
        /// </summary>
        public static string VerificationNoEmail {
            get {
                return ResourceManager.GetString("VerificationNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de 5 dígitos que enviamos a tu correo.
        /// </summary>
        public static string VerificationPrompt {
            get {
                return ResourceManager.GetString("VerificationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código.
        /// </summary>
        public static string VerificationTittle {
            get {
                return ResourceManager.GetString("VerificationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación.
        /// </summary>
        public static string VerificationWindowTitle {
            get {
                return ResourceManager.GetString("VerificationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:0}%.
        /// </summary>
        public static string VolumePercentageFormat {
            get {
                return ResourceManager.GetString("VolumePercentageFormat", resourceCulture);
            }
        }
    }
}
