//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominoTrainGame.Resources.Localization.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTAR.
        /// </summary>
        public static string AcceptReadyButtonLabel {
            get {
                return ResourceManager.GetString("AcceptReadyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / SEGURIDAD.
        /// </summary>
        public static string AccountSecuritySectionLabel {
            get {
                return ResourceManager.GetString("AccountSecuritySectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta?.
        /// </summary>
        public static string AlreadyHaveAccountLabel {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / AUDIO.
        /// </summary>
        public static string AudioSectionLabel {
            get {
                return ResourceManager.GetString("AudioSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVATAR.
        /// </summary>
        public static string AvatarSectionLabel {
            get {
                return ResourceManager.GetString("AvatarSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLVER.
        /// </summary>
        public static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a inicio de sesión.
        /// </summary>
        public static string BackToLoginLabel {
            get {
                return ResourceManager.GetString("BackToLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOGRAFÍA.
        /// </summary>
        public static string BiographyLabel {
            get {
                return ResourceManager.GetString("BiographyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGAR.
        /// </summary>
        public static string ButtonPlay {
            get {
                return ResourceManager.GetString("ButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Verificar.
        /// </summary>
        public static string ButtonVerify {
            get {
                return ResourceManager.GetString("ButtonVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELAR.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelEditAccessibleName {
            get {
                return ResourceManager.GetString("CancelEditAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string ChangePasswordButtonLabel {
            get {
                return ResourceManager.GetString("ChangePasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Cambiar contraseña.
        /// </summary>
        public static string ChangePasswordWindowTitle {
            get {
                return ResourceManager.GetString("ChangePasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMAR NUEVA CONTRASEÑA.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al registro.
        /// </summary>
        public static string CreateAccountAccessibleName {
            get {
                return ResourceManager.GetString("CreateAccountAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string CreateAccountLinkLabel {
            get {
                return ResourceManager.GetString("CreateAccountLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAR.
        /// </summary>
        public static string CreateGameButtonLabel {
            get {
                return ResourceManager.GetString("CreateGameButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepara la mesa, elige el doble máximo y comparte el código con tus amigos..
        /// </summary>
        public static string CreateGameDescription {
            get {
                return ResourceManager.GetString("CreateGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAR PARTIDA.
        /// </summary>
        public static string CreateGameTitle {
            get {
                return ResourceManager.GetString("CreateGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/ CREDENCIALES.
        /// </summary>
        public static string CredentialSectionLabel {
            get {
                return ResourceManager.GetString("CredentialSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA ACTUAL.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña actual..
        /// </summary>
        public static string CurrentPasswordRequiredMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al conectar con la base de datos..
        /// </summary>
        public static string DatabaseErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entiendo que esta acción no se puede deshacer..
        /// </summary>
        public static string DeleteAccountConfirmationLabel {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma que deseas eliminar tu cuenta..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña para confirmar tu identidad..
        /// </summary>
        public static string DeleteAccountPasswordHint {
            get {
                return ResourceManager.GetString("DeleteAccountPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR CUENTA.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez eliminada, no podrás recuperar tu cuenta..
        /// </summary>
        public static string DeleteAccountWarningDescription {
            get {
                return ResourceManager.GetString("DeleteAccountWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCIÓN PERMANENTE.
        /// </summary>
        public static string DeleteAccountWarningTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Eliminar cuenta.
        /// </summary>
        public static string DeleteAccountWindowTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble doce.
        /// </summary>
        public static string Double12AccessibleName {
            get {
                return ResourceManager.GetString("Double12AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Double12Label {
            get {
                return ResourceManager.GetString("Double12Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble seis.
        /// </summary>
        public static string Double6AccessibleName {
            get {
                return ResourceManager.GetString("Double6AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Double6Label {
            get {
                return ResourceManager.GetString("Double6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble nueve.
        /// </summary>
        public static string Double9AccessibleName {
            get {
                return ResourceManager.GetString("Double9AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Double9Label {
            get {
                return ResourceManager.GetString("Double9Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDITAR.
        /// </summary>
        public static string EditButtonLabel {
            get {
                return ResourceManager.GetString("EditButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de correo electrónico.
        /// </summary>
        public static string EmailAccessibleName {
            get {
                return ResourceManager.GetString("EmailAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREO ELECTRÓNICO.
        /// </summary>
        public static string EmailAdressLabel {
            get {
                return ResourceManager.GetString("EmailAdressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREO ELECTRÓNICO O USUARIO.
        /// </summary>
        public static string EmailOrUsernameLabel {
            get {
                return ResourceManager.GetString("EmailOrUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Los campos obligatorios no pueden estar vacíos.
        /// </summary>
        public static string EmptyFieldsMessage {
            get {
                return ResourceManager.GetString("EmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés / English.
        /// </summary>
        public static string EnglishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("EnglishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string EnglishLanguageCode {
            get {
                return ResourceManager.GetString("EnglishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string EnglishLanguageDescription {
            get {
                return ResourceManager.GetString("EnglishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR AL MENÚ.
        /// </summary>
        public static string ExitToMenuButtonLabel {
            get {
                return ResourceManager.GetString("ExitToMenuButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string ForgotPasswordAccessibleName {
            get {
                return ResourceManager.GetString("ForgotPasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTA DE AMIGOS.
        /// </summary>
        public static string FriendListWindowTitle {
            get {
                return ResourceManager.GetString("FriendListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTA DE AMIGOS.
        /// </summary>
        public static string FriendsListWindowTitle {
            get {
                return ResourceManager.GetString("FriendsListWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGLAS DEL JUEGO.
        /// </summary>
        public static string GameRulesButtonLabel {
            get {
                return ResourceManager.GetString("GameRulesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGLAS DEL JUEGO.
        /// </summary>
        public static string GameRulesTitle {
            get {
                return ResourceManager.GetString("GameRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Reglas del juego.
        /// </summary>
        public static string GameRulesWindowTitle {
            get {
                return ResourceManager.GetString("GameRulesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepara la mesa y reúne a tus compañeros de viaje..
        /// </summary>
        public static string GameSetupDescription {
            get {
                return ResourceManager.GetString("GameSetupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN DE PARTIDA.
        /// </summary>
        public static string GameSetupTitle {
            get {
                return ResourceManager.GetString("GameSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Configuración de partida.
        /// </summary>
        public static string GameSetupWindowTitle {
            get {
                return ResourceManager.GetString("GameSetupWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDAS JUGADAS.
        /// </summary>
        public static string GamesPlayedLabel {
            get {
                return ResourceManager.GetString("GamesPlayedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMINO TRAIN.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión.
        /// </summary>
        public static string GoToLoginLabel {
            get {
                return ResourceManager.GetString("GoToLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        public static string GuestButtonAccessibleName {
            get {
                return ResourceManager.GetString("GuestButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGAR COMO INVITADO.
        /// </summary>
        public static string GuestButtonLabel {
            get {
                return ResourceManager.GetString("GuestButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La contraseña debe tener al menos {0} caracteres.
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrarás el código en la pantalla de configuración de la partida..
        /// </summary>
        public static string InvitationCodeHint {
            get {
                return ResourceManager.GetString("InvitationCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO DE LA SALA.
        /// </summary>
        public static string InvitationCodeLabel {
            get {
                return ResourceManager.GetString("InvitationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce el código que te compartió el anfitrión de la partida..
        /// </summary>
        public static string InvitationDescription {
            get {
                return ResourceManager.GetString("InvitationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO DE
        ///INVITACIÓN.
        /// </summary>
        public static string InvitationTitle {
            get {
                return ResourceManager.GetString("InvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIRSE.
        /// </summary>
        public static string JoinGameButtonLabel {
            get {
                return ResourceManager.GetString("JoinGameButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una invitación? Introduce el código y toma tu lugar en la sala..
        /// </summary>
        public static string JoinGameDescription {
            get {
                return ResourceManager.GetString("JoinGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIRSE A PARTIDA.
        /// </summary>
        public static string JoinGameTitle {
            get {
                return ResourceManager.GetString("JoinGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Código de invitación.
        /// </summary>
        public static string JoinGameWindowTitle {
            get {
                return ResourceManager.GetString("JoinGameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRAR A LA SALA.
        /// </summary>
        public static string JoinRoomButtonLabel {
            get {
                return ResourceManager.GetString("JoinRoomButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una mesa compartida.
        ///Una nueva partida..
        /// </summary>
        public static string JoinSidebarDescription {
            get {
                return ResourceManager.GetString("JoinSidebarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TU LUGAR
        ///EN EL TREN.
        /// </summary>
        public static string JoinSidebarTitle {
            get {
                return ResourceManager.GetString("JoinSidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚNETE A LA MESA.
        /// </summary>
        public static string JoinTableTitle {
            get {
                return ResourceManager.GetString("JoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 / IDIOMA.
        /// </summary>
        public static string LanguageSectionLabel {
            get {
                return ResourceManager.GetString("LanguageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASIFICACIÓN.
        /// </summary>
        public static string LeaderboardButtonLabel {
            get {
                return ResourceManager.GetString("LeaderboardButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay puntuaciones de partidas terminadas..
        /// </summary>
        public static string LeaderboardEmptyMessage {
            get {
                return ResourceManager.GetString("LeaderboardEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación por victorias; los empates se ordenan por nombre. Solo se cuentan partidas terminadas. Pulsa un encabezado para ordenar. Los puntos son la suma de las penalizaciones de dominó..
        /// </summary>
        public static string LeaderboardExplanation {
            get {
                return ResourceManager.GetString("LeaderboardExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por jugador.
        /// </summary>
        public static string LeaderboardFilterLabel {
            get {
                return ResourceManager.GetString("LeaderboardFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIDAS.
        /// </summary>
        public static string LeaderboardGamesHeader {
            get {
                return ResourceManager.GetString("LeaderboardGamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron cargar las puntuaciones. Revisa la conexión e inténtalo de nuevo..
        /// </summary>
        public static string LeaderboardLoadErrorMessage {
            get {
                return ResourceManager.GetString("LeaderboardLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando puntuaciones….
        /// </summary>
        public static string LeaderboardLoadingMessage {
            get {
                return ResourceManager.GetString("LeaderboardLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay jugadores que coincidan con el filtro..
        /// </summary>
        public static string LeaderboardNoMatchesMessage {
            get {
                return ResourceManager.GetString("LeaderboardNoMatchesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGADOR.
        /// </summary>
        public static string LeaderboardPlayerHeader {
            get {
                return ResourceManager.GetString("LeaderboardPlayerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSICIÓN.
        /// </summary>
        public static string LeaderboardRankHeader {
            get {
                return ResourceManager.GetString("LeaderboardRankHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALIZAR.
        /// </summary>
        public static string LeaderboardRefreshButtonLabel {
            get {
                return ResourceManager.GetString("LeaderboardRefreshButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTOS.
        /// </summary>
        public static string LeaderboardScoreHeader {
            get {
                return ResourceManager.GetString("LeaderboardScoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASIFICACIÓN.
        /// </summary>
        public static string LeaderboardTitle {
            get {
                return ResourceManager.GetString("LeaderboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Clasificación.
        /// </summary>
        public static string LeaderboardWindowTitle {
            get {
                return ResourceManager.GetString("LeaderboardWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VICTORIAS.
        /// </summary>
        public static string LeaderboardWinsHeader {
            get {
                return ResourceManager.GetString("LeaderboardWinsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LoginButtonAccessibleName {
            get {
                return ResourceManager.GetString("LoginButtonAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAR SESIÓN.
        /// </summary>
        public static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de correo electrónico o usuario.
        /// </summary>
        public static string LoginIdentifierAccessibleName {
            get {
                return ResourceManager.GetString("LoginIdentifierAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORREO ELECTRÓNICO O USUARIO.
        /// </summary>
        public static string LoginIdentifierLabel {
            get {
                return ResourceManager.GetString("LoginIdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIO DE SESION.
        /// </summary>
        public static string LoginSectionTitle {
            get {
                return ResourceManager.GetString("LoginSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión para continuar tu partida.
        /// </summary>
        public static string LoginSidebarDescription {
            get {
                return ResourceManager.GetString("LoginSidebarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIO DE SESIÓN.
        /// </summary>
        public static string LoginSidebarLabel {
            get {
                return ResourceManager.GetString("LoginSidebarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIENVENIDO DE VUELTA.
        /// </summary>
        public static string LoginSidebarTitle {
            get {
                return ResourceManager.GetString("LoginSidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIENVENIDO DE VUELTA.
        /// </summary>
        public static string LoginSiderBarLabel {
            get {
                return ResourceManager.GetString("LoginSiderBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren de domino - Inicio de sesión.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERRAR SESIÓN.
        /// </summary>
        public static string LogOutSessionLabel {
            get {
                return ResourceManager.GetString("LogOutSessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCAR LISTO.
        /// </summary>
        public static string MarkReadyButtonLabel {
            get {
                return ResourceManager.GetString("MarkReadyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos por ronda y total acumulado..
        /// </summary>
        public static string MatchResultsDescription {
            get {
                return ResourceManager.GetString("MatchResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTAJES Y RESULTADOS.
        /// </summary>
        public static string MatchResultsTitle {
            get {
                return ResourceManager.GetString("MatchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Puntajes y resultados.
        /// </summary>
        public static string MatchResultsWindowTitle {
            get {
                return ResourceManager.GetString("MatchResultsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El doble máximo define el conjunto de fichas de la partida..
        /// </summary>
        public static string MaximumDoubleDescription {
            get {
                return ResourceManager.GetString("MaximumDoubleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOBLE MÁXIMO.
        /// </summary>
        public static string MaximumDoubleLabel {
            get {
                return ResourceManager.GetString("MaximumDoubleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado por el anfitrión..
        /// </summary>
        public static string MaximumDoubleReadOnlyDescription {
            get {
                return ResourceManager.GetString("MaximumDoubleReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIEMBRO DESDE.
        /// </summary>
        public static string MemberSinceLabel {
            get {
                return ResourceManager.GetString("MemberSinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es incorrecta..
        /// </summary>
        public static string MessageIncorrectPassword {
            get {
                return ResourceManager.GetString("MessageIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión correcto..
        /// </summary>
        public static string MessageLoginSuccess {
            get {
                return ResourceManager.GetString("MessageLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa los campos obligatorios..
        /// </summary>
        public static string MessageRequiredFields {
            get {
                return ResourceManager.GetString("MessageRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro completado correctamente..
        /// </summary>
        public static string MessageSignUpSuccess {
            get {
                return ResourceManager.GetString("MessageSignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario o correo ya está registrado..
        /// </summary>
        public static string MessageUserAlreadyExists {
            get {
                return ResourceManager.GetString("MessageUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado..
        /// </summary>
        public static string MessageUserNotFound {
            get {
                return ResourceManager.GetString("MessageUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico no es válido.
        /// </summary>
        public static string MesssageInvalidEmail {
            get {
                return ResourceManager.GetString("MesssageInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÚSICA.
        /// </summary>
        public static string MusicVolumeLabel {
            get {
                return ResourceManager.GetString("MusicVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige cómo quieres comenzar tu próximo viaje..
        /// </summary>
        public static string NewGameDescription {
            get {
                return ResourceManager.GetString("NewGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA PARTIDA.
        /// </summary>
        public static string NewGameTitle {
            get {
                return ResourceManager.GetString("NewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Nueva partida.
        /// </summary>
        public static string NewGameWindowTitle {
            get {
                return ResourceManager.GetString("NewGameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ NUEVO PASAJERO.
        /// </summary>
        public static string NewPassagerSubtitule {
            get {
                return ResourceManager.GetString("NewPassagerSubtitule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una contraseña diferente a la actual y confírmala..
        /// </summary>
        public static string NewPasswordHint {
            get {
                return ResourceManager.GetString("NewPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA CONTRASEÑA.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGUIENTE RONDA.
        /// </summary>
        public static string NextRoundButtonLabel {
            get {
                return ResourceManager.GetString("NextRoundButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        public static string NoAccountLabel {
            get {
                return ResourceManager.GetString("NoAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMIGOS.
        /// </summary>
        public static string OpenFriendsListLabel {
            get {
                return ResourceManager.GetString("OpenFriendsListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVA PARTIDA.
        /// </summary>
        public static string OpenNewGameLabel {
            get {
                return ResourceManager.GetString("OpenNewGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL.
        /// </summary>
        public static string OpenProfileButtonLabel {
            get {
                return ResourceManager.GetString("OpenProfileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +  Un lugar disponible.
        /// </summary>
        public static string OpenSeatLabel {
            get {
                return ResourceManager.GetString("OpenSeatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string OpenSettingsButtonLabel {
            get {
                return ResourceManager.GetString("OpenSettingsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de contraseña.
        /// </summary>
        public static string PasswordAccessibleName {
            get {
                return ResourceManager.GetString("PasswordAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compartas tu contraseña con otros jugadores..
        /// </summary>
        public static string PasswordPrivacyNote {
            get {
                return ResourceManager.GetString("PasswordPrivacyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGADORES.
        /// </summary>
        public static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL DEL JUGADOR.
        /// </summary>
        public static string ProfileSectionTitle {
            get {
                return ResourceManager.GetString("ProfileSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADÍSTICAS.
        /// </summary>
        public static string ProfileStatsSectionLabel {
            get {
                return ResourceManager.GetString("ProfileStatsSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Perfil.
        /// </summary>
        public static string ProfileWindowTitle {
            get {
                return ResourceManager.GetString("ProfileWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu próximo viaje comienza con una cuenta segura..
        /// </summary>
        public static string ProtectAccountDescription {
            get {
                return ResourceManager.GetString("ProtectAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo listo para compartir una nueva ronda..
        /// </summary>
        public static string ReadyRoomNote {
            get {
                return ResourceManager.GetString("ReadyRoomNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTO.
        /// </summary>
        public static string ReadyStatusLabel {
            get {
                return ResourceManager.GetString("ReadyStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECUPERAR CONTRASEÑA.
        /// </summary>
        public static string RecoverPasswordFormTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Recuperar contraseña.
        /// </summary>
        public static string RecoverPasswordWindowTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma asiento y regístrate para comenzar tu partida.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRO.
        /// </summary>
        public static string RegisterSectionTitle {
            get {
                return ResourceManager.GetString("RegisterSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro completado correctamente.
        /// </summary>
        public static string RegisterSucessMessage {
            get {
                return ResourceManager.GetString("RegisterSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string RegisterTittle {
            get {
                return ResourceManager.GetString("RegisterTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe el motivo del reporte..
        /// </summary>
        public static string ReportPlayerDescription {
            get {
                return ResourceManager.GetString("ReportPlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes proporcionar un motivo para el reporte..
        /// </summary>
        public static string ReportReasonRequiredMessage {
            get {
                return ResourceManager.GetString("ReportReasonRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparte este código con tus amigos..
        /// </summary>
        public static string RoomCodeDescription {
            get {
                return ResourceManager.GetString("RoomCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓDIGO DE PARTIDA.
        /// </summary>
        public static string RoomCodeLabel {
            get {
                return ResourceManager.GetString("RoomCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANFITRIÓN.
        /// </summary>
        public static string RoomHostLabel {
            get {
                return ResourceManager.GetString("RoomHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay jugadores en la sala..
        /// </summary>
        public static string RoomNoPlayersLabel {
            get {
                return ResourceManager.GetString("RoomNoPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO LISTO.
        /// </summary>
        public static string RoomNotReadyLabel {
            get {
                return ResourceManager.GetString("RoomNotReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string RoomPlayerCountFormat {
            get {
                return ResourceManager.GetString("RoomPlayerCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALA DE PARTIDA.
        /// </summary>
        public static string RoomTitle {
            get {
                return ResourceManager.GetString("RoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Sala de partida.
        /// </summary>
        public static string RoomWindowTitle {
            get {
                return ResourceManager.GetString("RoomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Después de colocar un doble, juega otra ficha. Un doble pendiente debe cubrirse antes de continuar en otros trenes..
        /// </summary>
        public static string RulesDoublesDescription {
            get {
                return ResourceManager.GetString("RulesDoublesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05/FICHAS DOBLES.
        /// </summary>
        public static string RulesDoublesTitle {
            get {
                return ResourceManager.GetString("RulesDoublesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no puedes jugar, roba una ficha. Si tampoco puedes colocarla, pasa y deja tu tren abierto a los demás..
        /// </summary>
        public static string RulesDrawDescription {
            get {
                return ResourceManager.GetString("RulesDrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04/ROBAR Y PASAR.
        /// </summary>
        public static string RulesDrawTitle {
            get {
                return ResourceManager.GetString("RulesDrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloca tus fichas y termina con la menor cantidad de puntos. Al final de la partida, gana el menor total..
        /// </summary>
        public static string RulesObjectiveDescription {
            get {
                return ResourceManager.GetString("RulesObjectiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/OBJETIVO.
        /// </summary>
        public static string RulesObjectiveTitle {
            get {
                return ResourceManager.GetString("RulesObjectiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El doble inicial se coloca en el centro. Cada jugador tiene un tren y las fichas restantes forman el pozo..
        /// </summary>
        public static string RulesPreparationDescription {
            get {
                return ResourceManager.GetString("RulesPreparationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02/PREPARACIÓN.
        /// </summary>
        public static string RulesPreparationTitle {
            get {
                return ResourceManager.GetString("RulesPreparationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ronda termina al agotarse una mano o bloquearse la mesa. Suma los puntos de tus fichas restantes a tu total..
        /// </summary>
        public static string RulesScoringDescription {
            get {
                return ResourceManager.GetString("RulesScoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06/FIN DE LA RONDA.
        /// </summary>
        public static string RulesScoringTitle {
            get {
                return ResourceManager.GetString("RulesScoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une una ficha por un extremo del mismo valor. Puedes jugar en tu tren, en el tren mexicano o en un tren abierto..
        /// </summary>
        public static string RulesTurnDescription {
            get {
                return ResourceManager.GetString("RulesTurnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03/EN TU TURNO.
        /// </summary>
        public static string RulesTurnTitle {
            get {
                return ResourceManager.GetString("RulesTurnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo 1.
        /// </summary>
        public static string SampleFriendOne {
            get {
                return ResourceManager.GetString("SampleFriendOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string SampleFriendOneRoundOne {
            get {
                return ResourceManager.GetString("SampleFriendOneRoundOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string SampleFriendOneRoundTwo {
            get {
                return ResourceManager.GetString("SampleFriendOneRoundTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string SampleFriendOneTotal {
            get {
                return ResourceManager.GetString("SampleFriendOneTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo 3.
        /// </summary>
        public static string SampleFriendThree {
            get {
                return ResourceManager.GetString("SampleFriendThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string SampleFriendThreeRoundOne {
            get {
                return ResourceManager.GetString("SampleFriendThreeRoundOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string SampleFriendThreeRoundTwo {
            get {
                return ResourceManager.GetString("SampleFriendThreeRoundTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string SampleFriendThreeTotal {
            get {
                return ResourceManager.GetString("SampleFriendThreeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo 2.
        /// </summary>
        public static string SampleFriendTwo {
            get {
                return ResourceManager.GetString("SampleFriendTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 / 4.
        /// </summary>
        public static string SamplePlayerCount {
            get {
                return ResourceManager.GetString("SamplePlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXXXX.
        /// </summary>
        public static string SampleRoomCode {
            get {
                return ResourceManager.GetString("SampleRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡AMIGO 2 GANÓ!.
        /// </summary>
        public static string SampleWinnerLabel {
            get {
                return ResourceManager.GetString("SampleWinnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SampleWinnerScore {
            get {
                return ResourceManager.GetString("SampleWinnerScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47.
        /// </summary>
        public static string SampleYouRoundOne {
            get {
                return ResourceManager.GetString("SampleYouRoundOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string SampleYouRoundTwo {
            get {
                return ResourceManager.GetString("SampleYouRoundTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55.
        /// </summary>
        public static string SampleYouTotal {
            get {
                return ResourceManager.GetString("SampleYouTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUARDAR.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveProfileAccessibleName {
            get {
                return ResourceManager.GetString("SaveProfileAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores conectados: {0}.
        /// </summary>
        public static string ScoreConnectedPlayersFormat {
            get {
                return ResourceManager.GetString("ScoreConnectedPlayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menos puntos, mejor resultado..
        /// </summary>
        public static string ScoreExplanation {
            get {
                return ResourceManager.GetString("ScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay jugadores ni resultados para mostrar..
        /// </summary>
        public static string ScoreNoPlayersLabel {
            get {
                return ResourceManager.GetString("ScoreNoPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULTADOS PENDIENTES.
        /// </summary>
        public static string ScorePendingResultsLabel {
            get {
                return ResourceManager.GetString("ScorePendingResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUGADOR.
        /// </summary>
        public static string ScorePlayerLabel {
            get {
                return ResourceManager.GetString("ScorePlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rondas: {0}.
        /// </summary>
        public static string ScoreRoundCountFormat {
            get {
                return ResourceManager.GetString("ScoreRoundCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RONDA {0}.
        /// </summary>
        public static string ScoreRoundFormat {
            get {
                return ResourceManager.GetString("ScoreRoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RONDA 1.
        /// </summary>
        public static string ScoreRoundOneLabel {
            get {
                return ResourceManager.GetString("ScoreRoundOneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RONDA 2.
        /// </summary>
        public static string ScoreRoundTwoLabel {
            get {
                return ResourceManager.GetString("ScoreRoundTwoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPATE: {0}.
        /// </summary>
        public static string ScoreTieFormat {
            get {
                return ResourceManager.GetString("ScoreTieFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string ScoreTotalLabel {
            get {
                return ResourceManager.GetString("ScoreTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GANADOR: {0}.
        /// </summary>
        public static string ScoreWinnerFormat {
            get {
                return ResourceManager.GetString("ScoreWinnerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Configuración.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepta tu lugar para pasar a la sala de espera..
        /// </summary>
        public static string SetupRoomNote {
            get {
                return ResourceManager.GetString("SetupRoomNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRARSE.
        /// </summary>
        public static string SignUpBottonLabel {
            get {
                return ResourceManager.GetString("SignUpBottonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar nueva cuenta.
        /// </summary>
        public static string SignUpButtonAccesibleName {
            get {
                return ResourceManager.GetString("SignUpButtonAccesibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren de domino - Inicio de sesión.
        /// </summary>
        public static string SignUpWindowTitle {
            get {
                return ResourceManager.GetString("SignUpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFECTOS DE SONIDO.
        /// </summary>
        public static string SoundEffectsVolumeLabel {
            get {
                return ResourceManager.GetString("SoundEffectsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string SpanishLanguageAccessibleName {
            get {
                return ResourceManager.GetString("SpanishLanguageAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES.
        /// </summary>
        public static string SpanishLanguageCode {
            get {
                return ResourceManager.GetString("SpanishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SpanishLanguageDescription {
            get {
                return ResourceManager.GetString("SpanishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string SpanishLanguageName {
            get {
                return ResourceManager.GetString("SpanishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAR.
        /// </summary>
        public static string StartMatchButtonLabel {
            get {
                return ResourceManager.GetString("StartMatchButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string TabFriends {
            get {
                return ResourceManager.GetString("TabFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes.
        /// </summary>
        public static string TabRequests {
            get {
                return ResourceManager.GetString("TabRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTUALIZAR.
        /// </summary>
        public static string UpdatePasswordButtonLabel {
            get {
                return ResourceManager.GetString("UpdatePasswordButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de nombre de usuario.
        /// </summary>
        public static string UsernameAccessibleName {
            get {
                return ResourceManager.GetString("UsernameAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE DE USUARIO.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código.
        /// </summary>
        public static string VerificationTitle {
            get {
                return ResourceManager.GetString("VerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTAJES.
        /// </summary>
        public static string ViewScoresButtonLabel {
            get {
                return ResourceManager.GetString("ViewScoresButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}%.
        /// </summary>
        public static string VolumePercentageFormat {
            get {
                return ResourceManager.GetString("VolumePercentageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mesa está preparada. El próximo viaje está por comenzar..
        /// </summary>
        public static string WaitingRoomDescription {
            get {
                return ResourceManager.GetString("WaitingRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALA DE ESPERA.
        /// </summary>
        public static string WaitingRoomTitle {
            get {
                return ResourceManager.GetString("WaitingRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train · Sala de espera.
        /// </summary>
        public static string WaitingRoomWindowTitle {
            get {
                return ResourceManager.GetString("WaitingRoomWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VICTORIAS.
        /// </summary>
        public static string WinsLabel {
            get {
                return ResourceManager.GetString("WinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú (anfitrión).
        /// </summary>
        public static string YouHostLabel {
            get {
                return ResourceManager.GetString("YouHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú.
        /// </summary>
        public static string YouPlayerLabel {
            get {
                return ResourceManager.GetString("YouPlayerLabel", resourceCulture);
            }
        }
    }
}
