// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame.Resources.Localization;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
    "System.Resources.Tools.StronglyTypedResourceBuilder",
    "18.0.0.0"
)]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class UiStrings
{
    private static global::System.Resources.ResourceManager _resourceManager;
    private static global::System.Globalization.CultureInfo _resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        "Microsoft.Performance",
        "CA1811:AvoidUncalledPrivateCode"
    )]
    internal UiStrings()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced
    )]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(_resourceManager, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                    "DominoTrainGame.Resources.Localization.UiStrings",
                    typeof(UiStrings).Assembly
                );
                _resourceManager = temp;
            }

            return _resourceManager;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced
    )]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return _resourceCulture;
        }

        set
        {
            _resourceCulture = value;
        }
    }

    public static string AcceptReadyButtonLabel
    {
        get
        {
            return ResourceManager.GetString("AcceptReadyButtonLabel", _resourceCulture);
        }
    }

    public static string AccountSecuritySectionLabel
    {
        get
        {
            return ResourceManager.GetString("AccountSecuritySectionLabel", _resourceCulture);
        }
    }

    public static string AlreadyHaveAccountLabel
    {
        get
        {
            return ResourceManager.GetString("AlreadyHaveAccountLabel", _resourceCulture);
        }
    }

    public static string AudioSectionLabel
    {
        get
        {
            return ResourceManager.GetString("AudioSectionLabel", _resourceCulture);
        }
    }

    public static string AvatarSectionLabel
    {
        get
        {
            return ResourceManager.GetString("AvatarSectionLabel", _resourceCulture);
        }
    }

    public static string BackButtonLabel
    {
        get
        {
            return ResourceManager.GetString("BackButtonLabel", _resourceCulture);
        }
    }

    public static string BackToLoginLabel
    {
        get
        {
            return ResourceManager.GetString("BackToLoginLabel", _resourceCulture);
        }
    }

    public static string BiographyLabel
    {
        get
        {
            return ResourceManager.GetString("BiographyLabel", _resourceCulture);
        }
    }

    public static string ButtonAccept
    {
        get
        {
            return ResourceManager.GetString("ButtonAccept", _resourceCulture);
        }
    }

    public static string ButtonAdd
    {
        get
        {
            return ResourceManager.GetString("ButtonAdd", _resourceCulture);
        }
    }

    public static string ButtonExit
    {
        get
        {
            return ResourceManager.GetString("ButtonExit", _resourceCulture);
        }
    }

    public static string ButtonPlay
    {
        get
        {
            return ResourceManager.GetString("ButtonPlay", _resourceCulture);
        }
    }

    public static string ButtonReject
    {
        get
        {
            return ResourceManager.GetString("ButtonReject", _resourceCulture);
        }
    }

    public static string ButtonRemove
    {
        get
        {
            return ResourceManager.GetString("ButtonRemove", _resourceCulture);
        }
    }

    public static string ButtonVerify
    {
        get
        {
            return ResourceManager.GetString("ButtonVerify", _resourceCulture);
        }
    }

    public static string CancelButtonLabel
    {
        get
        {
            return ResourceManager.GetString("CancelButtonLabel", _resourceCulture);
        }
    }

    public static string CancelEditAccessibleName
    {
        get
        {
            return ResourceManager.GetString("CancelEditAccessibleName", _resourceCulture);
        }
    }

    public static string ChangePasswordButtonLabel
    {
        get
        {
            return ResourceManager.GetString("ChangePasswordButtonLabel", _resourceCulture);
        }
    }

    public static string ChangePasswordTitle
    {
        get
        {
            return ResourceManager.GetString("ChangePasswordTitle", _resourceCulture);
        }
    }

    public static string ChangePasswordWindowTitle
    {
        get
        {
            return ResourceManager.GetString("ChangePasswordWindowTitle", _resourceCulture);
        }
    }

    public static string ConfirmPasswordLabel
    {
        get
        {
            return ResourceManager.GetString("ConfirmPasswordLabel", _resourceCulture);
        }
    }

    public static string CreateAccountAccessibleName
    {
        get
        {
            return ResourceManager.GetString("CreateAccountAccessibleName", _resourceCulture);
        }
    }

    public static string CreateAccountLinkLabel
    {
        get
        {
            return ResourceManager.GetString("CreateAccountLinkLabel", _resourceCulture);
        }
    }

    public static string CreateGameButtonLabel
    {
        get
        {
            return ResourceManager.GetString("CreateGameButtonLabel", _resourceCulture);
        }
    }

    public static string CreateGameDescription
    {
        get
        {
            return ResourceManager.GetString("CreateGameDescription", _resourceCulture);
        }
    }

    public static string CreateGameTitle
    {
        get
        {
            return ResourceManager.GetString("CreateGameTitle", _resourceCulture);
        }
    }

    public static string CredentialSectionLabel
    {
        get
        {
            return ResourceManager.GetString("CredentialSectionLabel", _resourceCulture);
        }
    }

    public static string CurrentPasswordLabel
    {
        get
        {
            return ResourceManager.GetString("CurrentPasswordLabel", _resourceCulture);
        }
    }

    public static string CurrentPasswordRequiredMessage
    {
        get
        {
            return ResourceManager.GetString("CurrentPasswordRequiredMessage", _resourceCulture);
        }
    }

    public static string DatabaseErrorMessage
    {
        get
        {
            return ResourceManager.GetString("DatabaseErrorMessage", _resourceCulture);
        }
    }

    public static string DeleteAccountConfirmationLabel
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountConfirmationLabel", _resourceCulture);
        }
    }

    public static string DeleteAccountDescription
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountDescription", _resourceCulture);
        }
    }

    public static string DeleteAccountPasswordHint
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountPasswordHint", _resourceCulture);
        }
    }

    public static string DeleteAccountTitle
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountTitle", _resourceCulture);
        }
    }

    public static string DeleteAccountWarningDescription
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountWarningDescription", _resourceCulture);
        }
    }

    public static string DeleteAccountWarningTitle
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountWarningTitle", _resourceCulture);
        }
    }

    public static string DeleteAccountWindowTitle
    {
        get
        {
            return ResourceManager.GetString("DeleteAccountWindowTitle", _resourceCulture);
        }
    }

    public static string Double12AccessibleName
    {
        get
        {
            return ResourceManager.GetString("Double12AccessibleName", _resourceCulture);
        }
    }

    public static string Double12Label
    {
        get
        {
            return ResourceManager.GetString("Double12Label", _resourceCulture);
        }
    }

    public static string Double6AccessibleName
    {
        get
        {
            return ResourceManager.GetString("Double6AccessibleName", _resourceCulture);
        }
    }

    public static string Double6Label
    {
        get
        {
            return ResourceManager.GetString("Double6Label", _resourceCulture);
        }
    }

    public static string Double9AccessibleName
    {
        get
        {
            return ResourceManager.GetString("Double9AccessibleName", _resourceCulture);
        }
    }

    public static string Double9Label
    {
        get
        {
            return ResourceManager.GetString("Double9Label", _resourceCulture);
        }
    }

    public static string EditButtonLabel
    {
        get
        {
            return ResourceManager.GetString("EditButtonLabel", _resourceCulture);
        }
    }

    public static string EmailAccessibleName
    {
        get
        {
            return ResourceManager.GetString("EmailAccessibleName", _resourceCulture);
        }
    }

    public static string EmailAdressLabel
    {
        get
        {
            return ResourceManager.GetString("EmailAdressLabel", _resourceCulture);
        }
    }

    public static string EmailOrUsernameLabel
    {
        get
        {
            return ResourceManager.GetString("EmailOrUsernameLabel", _resourceCulture);
        }
    }

    public static string EmptyFieldsMessage
    {
        get
        {
            return ResourceManager.GetString("EmptyFieldsMessage", _resourceCulture);
        }
    }

    public static string EnglishLanguageAccessibleName
    {
        get
        {
            return ResourceManager.GetString("EnglishLanguageAccessibleName", _resourceCulture);
        }
    }

    public static string EnglishLanguageCode
    {
        get
        {
            return ResourceManager.GetString("EnglishLanguageCode", _resourceCulture);
        }
    }

    public static string EnglishLanguageDescription
    {
        get
        {
            return ResourceManager.GetString("EnglishLanguageDescription", _resourceCulture);
        }
    }

    public static string EnglishLanguageName
    {
        get
        {
            return ResourceManager.GetString("EnglishLanguageName", _resourceCulture);
        }
    }

    public static string ExitToMenuButtonLabel
    {
        get
        {
            return ResourceManager.GetString("ExitToMenuButtonLabel", _resourceCulture);
        }
    }

    public static string ForgotPasswordAccessibleName
    {
        get
        {
            return ResourceManager.GetString("ForgotPasswordAccessibleName", _resourceCulture);
        }
    }

    public static string ForgotPasswordLabel
    {
        get
        {
            return ResourceManager.GetString("ForgotPasswordLabel", _resourceCulture);
        }
    }

    public static string FriendListWindowTitle
    {
        get
        {
            return ResourceManager.GetString("FriendListWindowTitle", _resourceCulture);
        }
    }

    public static string FriendsListWindowTitle
    {
        get
        {
            return ResourceManager.GetString("FriendsListWindowTitle", _resourceCulture);
        }
    }

    public static string GameRulesButtonLabel
    {
        get
        {
            return ResourceManager.GetString("GameRulesButtonLabel", _resourceCulture);
        }
    }

    public static string GameRulesTitle
    {
        get
        {
            return ResourceManager.GetString("GameRulesTitle", _resourceCulture);
        }
    }

    public static string GameRulesWindowTitle
    {
        get
        {
            return ResourceManager.GetString("GameRulesWindowTitle", _resourceCulture);
        }
    }

    public static string GameSetupDescription
    {
        get
        {
            return ResourceManager.GetString("GameSetupDescription", _resourceCulture);
        }
    }

    public static string GameSetupTitle
    {
        get
        {
            return ResourceManager.GetString("GameSetupTitle", _resourceCulture);
        }
    }

    public static string GameSetupWindowTitle
    {
        get
        {
            return ResourceManager.GetString("GameSetupWindowTitle", _resourceCulture);
        }
    }

    public static string GamesPlayedLabel
    {
        get
        {
            return ResourceManager.GetString("GamesPlayedLabel", _resourceCulture);
        }
    }

    public static string GameTitle
    {
        get
        {
            return ResourceManager.GetString("GameTitle", _resourceCulture);
        }
    }

    public static string GoToLoginLabel
    {
        get
        {
            return ResourceManager.GetString("GoToLoginLabel", _resourceCulture);
        }
    }

    public static string GuestButtonAccessibleName
    {
        get
        {
            return ResourceManager.GetString("GuestButtonAccessibleName", _resourceCulture);
        }
    }

    public static string GuestButtonLabel
    {
        get
        {
            return ResourceManager.GetString("GuestButtonLabel", _resourceCulture);
        }
    }

    public static string InvalidPasswordMessage
    {
        get
        {
            return ResourceManager.GetString("InvalidPasswordMessage", _resourceCulture);
        }
    }

    public static string InvitationCodeHint
    {
        get
        {
            return ResourceManager.GetString("InvitationCodeHint", _resourceCulture);
        }
    }

    public static string InvitationCodeLabel
    {
        get
        {
            return ResourceManager.GetString("InvitationCodeLabel", _resourceCulture);
        }
    }

    public static string InvitationDescription
    {
        get
        {
            return ResourceManager.GetString("InvitationDescription", _resourceCulture);
        }
    }

    public static string InvitationTitle
    {
        get
        {
            return ResourceManager.GetString("InvitationTitle", _resourceCulture);
        }
    }

    public static string JoinGameButtonLabel
    {
        get
        {
            return ResourceManager.GetString("JoinGameButtonLabel", _resourceCulture);
        }
    }

    public static string JoinGameDescription
    {
        get
        {
            return ResourceManager.GetString("JoinGameDescription", _resourceCulture);
        }
    }

    public static string JoinGameTitle
    {
        get
        {
            return ResourceManager.GetString("JoinGameTitle", _resourceCulture);
        }
    }

    public static string JoinGameWindowTitle
    {
        get
        {
            return ResourceManager.GetString("JoinGameWindowTitle", _resourceCulture);
        }
    }

    public static string JoinRoomButtonLabel
    {
        get
        {
            return ResourceManager.GetString("JoinRoomButtonLabel", _resourceCulture);
        }
    }

    public static string JoinSidebarDescription
    {
        get
        {
            return ResourceManager.GetString("JoinSidebarDescription", _resourceCulture);
        }
    }

    public static string JoinSidebarTitle
    {
        get
        {
            return ResourceManager.GetString("JoinSidebarTitle", _resourceCulture);
        }
    }

    public static string JoinTableTitle
    {
        get
        {
            return ResourceManager.GetString("JoinTableTitle", _resourceCulture);
        }
    }

    public static string LanguageSectionLabel
    {
        get
        {
            return ResourceManager.GetString("LanguageSectionLabel", _resourceCulture);
        }
    }

    public static string LeaderboardButtonLabel
    {
        get
        {
            return ResourceManager.GetString("LeaderboardButtonLabel", _resourceCulture);
        }
    }

    public static string LeaderboardEmptyMessage
    {
        get
        {
            return ResourceManager.GetString("LeaderboardEmptyMessage", _resourceCulture);
        }
    }

    public static string LeaderboardGamesHeader
    {
        get
        {
            return ResourceManager.GetString("LeaderboardGamesHeader", _resourceCulture);
        }
    }

    public static string LeaderboardLoadErrorMessage
    {
        get
        {
            return ResourceManager.GetString("LeaderboardLoadErrorMessage", _resourceCulture);
        }
    }

    public static string LeaderboardLoadingMessage
    {
        get
        {
            return ResourceManager.GetString("LeaderboardLoadingMessage", _resourceCulture);
        }
    }

    public static string LeaderboardNoMatchesMessage
    {
        get
        {
            return ResourceManager.GetString("LeaderboardNoMatchesMessage", _resourceCulture);
        }
    }

    public static string LeaderboardPlayerHeader
    {
        get
        {
            return ResourceManager.GetString("LeaderboardPlayerHeader", _resourceCulture);
        }
    }

    public static string LeaderboardRankHeader
    {
        get
        {
            return ResourceManager.GetString("LeaderboardRankHeader", _resourceCulture);
        }
    }

    public static string LeaderboardTitle
    {
        get
        {
            return ResourceManager.GetString("LeaderboardTitle", _resourceCulture);
        }
    }

    public static string LeaderboardWindowTitle
    {
        get
        {
            return ResourceManager.GetString("LeaderboardWindowTitle", _resourceCulture);
        }
    }

    public static string LeaderboardWinsHeader
    {
        get
        {
            return ResourceManager.GetString("LeaderboardWinsHeader", _resourceCulture);
        }
    }

    public static string LoginButtonAccessibleName
    {
        get
        {
            return ResourceManager.GetString("LoginButtonAccessibleName", _resourceCulture);
        }
    }

    public static string LoginButtonLabel
    {
        get
        {
            return ResourceManager.GetString("LoginButtonLabel", _resourceCulture);
        }
    }

    public static string LoginIdentifierAccessibleName
    {
        get
        {
            return ResourceManager.GetString("LoginIdentifierAccessibleName", _resourceCulture);
        }
    }

    public static string LoginIdentifierLabel
    {
        get
        {
            return ResourceManager.GetString("LoginIdentifierLabel", _resourceCulture);
        }
    }

    public static string LoginSectionTitle
    {
        get
        {
            return ResourceManager.GetString("LoginSectionTitle", _resourceCulture);
        }
    }

    public static string LoginSidebarDescription
    {
        get
        {
            return ResourceManager.GetString("LoginSidebarDescription", _resourceCulture);
        }
    }

    public static string LoginSidebarLabel
    {
        get
        {
            return ResourceManager.GetString("LoginSidebarLabel", _resourceCulture);
        }
    }

    public static string LoginSidebarTitle
    {
        get
        {
            return ResourceManager.GetString("LoginSidebarTitle", _resourceCulture);
        }
    }

    public static string LoginSiderBarLabel
    {
        get
        {
            return ResourceManager.GetString("LoginSiderBarLabel", _resourceCulture);
        }
    }

    public static string LoginWindowTitle
    {
        get
        {
            return ResourceManager.GetString("LoginWindowTitle", _resourceCulture);
        }
    }

    public static string LogOutSessionLabel
    {
        get
        {
            return ResourceManager.GetString("LogOutSessionLabel", _resourceCulture);
        }
    }

    public static string MainWindowTitle
    {
        get
        {
            return ResourceManager.GetString("MainWindowTitle", _resourceCulture);
        }
    }

    public static string MarkReadyButtonLabel
    {
        get
        {
            return ResourceManager.GetString("MarkReadyButtonLabel", _resourceCulture);
        }
    }

    public static string MatchResultsDescription
    {
        get
        {
            return ResourceManager.GetString("MatchResultsDescription", _resourceCulture);
        }
    }

    public static string MatchResultsTitle
    {
        get
        {
            return ResourceManager.GetString("MatchResultsTitle", _resourceCulture);
        }
    }

    public static string MatchResultsWindowTitle
    {
        get
        {
            return ResourceManager.GetString("MatchResultsWindowTitle", _resourceCulture);
        }
    }

    public static string MaximumDoubleDescription
    {
        get
        {
            return ResourceManager.GetString("MaximumDoubleDescription", _resourceCulture);
        }
    }

    public static string MaximumDoubleLabel
    {
        get
        {
            return ResourceManager.GetString("MaximumDoubleLabel", _resourceCulture);
        }
    }

    public static string MaximumDoubleReadOnlyDescription
    {
        get
        {
            return ResourceManager.GetString("MaximumDoubleReadOnlyDescription", _resourceCulture);
        }
    }

    public static string MemberSinceLabel
    {
        get
        {
            return ResourceManager.GetString("MemberSinceLabel", _resourceCulture);
        }
    }

    public static string MessageIncorrectPassword
    {
        get
        {
            return ResourceManager.GetString("MessageIncorrectPassword", _resourceCulture);
        }
    }

    public static string MessageLoginSuccess
    {
        get
        {
            return ResourceManager.GetString("MessageLoginSuccess", _resourceCulture);
        }
    }

    public static string MessageRequiredFields
    {
        get
        {
            return ResourceManager.GetString("MessageRequiredFields", _resourceCulture);
        }
    }

    public static string MessageSignUpSuccess
    {
        get
        {
            return ResourceManager.GetString("MessageSignUpSuccess", _resourceCulture);
        }
    }

    public static string MessageUserAlreadyExists
    {
        get
        {
            return ResourceManager.GetString("MessageUserAlreadyExists", _resourceCulture);
        }
    }

    public static string MessageUserNotFound
    {
        get
        {
            return ResourceManager.GetString("MessageUserNotFound", _resourceCulture);
        }
    }

    public static string MesssageInvalidEmail
    {
        get
        {
            return ResourceManager.GetString("MesssageInvalidEmail", _resourceCulture);
        }
    }

    public static string MusicVolumeLabel
    {
        get
        {
            return ResourceManager.GetString("MusicVolumeLabel", _resourceCulture);
        }
    }

    public static string NewGameDescription
    {
        get
        {
            return ResourceManager.GetString("NewGameDescription", _resourceCulture);
        }
    }

    public static string NewGameTitle
    {
        get
        {
            return ResourceManager.GetString("NewGameTitle", _resourceCulture);
        }
    }

    public static string NewGameWindowTitle
    {
        get
        {
            return ResourceManager.GetString("NewGameWindowTitle", _resourceCulture);
        }
    }

    public static string NewPassagerSubtitule
    {
        get
        {
            return ResourceManager.GetString("NewPassagerSubtitule", _resourceCulture);
        }
    }

    public static string NewPasswordHint
    {
        get
        {
            return ResourceManager.GetString("NewPasswordHint", _resourceCulture);
        }
    }

    public static string NewPasswordLabel
    {
        get
        {
            return ResourceManager.GetString("NewPasswordLabel", _resourceCulture);
        }
    }

    public static string NextRoundButtonLabel
    {
        get
        {
            return ResourceManager.GetString("NextRoundButtonLabel", _resourceCulture);
        }
    }

    public static string NoAccountLabel
    {
        get
        {
            return ResourceManager.GetString("NoAccountLabel", _resourceCulture);
        }
    }

    public static string OpenFriendsListLabel
    {
        get
        {
            return ResourceManager.GetString("OpenFriendsListLabel", _resourceCulture);
        }
    }

    public static string OpenNewGameLabel
    {
        get
        {
            return ResourceManager.GetString("OpenNewGameLabel", _resourceCulture);
        }
    }

    public static string OpenProfileButtonLabel
    {
        get
        {
            return ResourceManager.GetString("OpenProfileButtonLabel", _resourceCulture);
        }
    }

    public static string OpenSeatLabel
    {
        get
        {
            return ResourceManager.GetString("OpenSeatLabel", _resourceCulture);
        }
    }

    public static string OpenSettingsButtonLabel
    {
        get
        {
            return ResourceManager.GetString("OpenSettingsButtonLabel", _resourceCulture);
        }
    }

    public static string PasswordAccessibleName
    {
        get
        {
            return ResourceManager.GetString("PasswordAccessibleName", _resourceCulture);
        }
    }

    public static string PasswordLabel
    {
        get
        {
            return ResourceManager.GetString("PasswordLabel", _resourceCulture);
        }
    }

    public static string PasswordPrivacyNote
    {
        get
        {
            return ResourceManager.GetString("PasswordPrivacyNote", _resourceCulture);
        }
    }

    public static string PasswordsDoNotMatchMessage
    {
        get
        {
            return ResourceManager.GetString("PasswordsDoNotMatchMessage", _resourceCulture);
        }
    }

    public static string PlayersLabel
    {
        get
        {
            return ResourceManager.GetString("PlayersLabel", _resourceCulture);
        }
    }

    public static string ProfileSectionTitle
    {
        get
        {
            return ResourceManager.GetString("ProfileSectionTitle", _resourceCulture);
        }
    }

    public static string ProfileStatsSectionLabel
    {
        get
        {
            return ResourceManager.GetString("ProfileStatsSectionLabel", _resourceCulture);
        }
    }

    public static string ProfileWindowTitle
    {
        get
        {
            return ResourceManager.GetString("ProfileWindowTitle", _resourceCulture);
        }
    }

    public static string ProtectAccountDescription
    {
        get
        {
            return ResourceManager.GetString("ProtectAccountDescription", _resourceCulture);
        }
    }

    public static string ReadyRoomNote
    {
        get
        {
            return ResourceManager.GetString("ReadyRoomNote", _resourceCulture);
        }
    }

    public static string ReadyStatusLabel
    {
        get
        {
            return ResourceManager.GetString("ReadyStatusLabel", _resourceCulture);
        }
    }

    public static string RecoverPasswordFormTitle
    {
        get
        {
            return ResourceManager.GetString("RecoverPasswordFormTitle", _resourceCulture);
        }
    }

    public static string RecoverPasswordSuccessMessage
    {
        get
        {
            return ResourceManager.GetString("RecoverPasswordSuccessMessage", _resourceCulture);
        }
    }

    public static string RecoverPasswordWindowTitle
    {
        get
        {
            return ResourceManager.GetString("RecoverPasswordWindowTitle", _resourceCulture);
        }
    }

    public static string RegisterDescription
    {
        get
        {
            return ResourceManager.GetString("RegisterDescription", _resourceCulture);
        }
    }

    public static string RegisterSectionTitle
    {
        get
        {
            return ResourceManager.GetString("RegisterSectionTitle", _resourceCulture);
        }
    }

    public static string RegisterSucessMessage
    {
        get
        {
            return ResourceManager.GetString("RegisterSucessMessage", _resourceCulture);
        }
    }

    public static string RegisterTittle
    {
        get
        {
            return ResourceManager.GetString("RegisterTittle", _resourceCulture);
        }
    }

    public static string ReportPlayerDescription
    {
        get
        {
            return ResourceManager.GetString("ReportPlayerDescription", _resourceCulture);
        }
    }

    public static string ReportReasonRequiredMessage
    {
        get
        {
            return ResourceManager.GetString("ReportReasonRequiredMessage", _resourceCulture);
        }
    }

    public static string RoomCodeDescription
    {
        get
        {
            return ResourceManager.GetString("RoomCodeDescription", _resourceCulture);
        }
    }

    public static string RoomCodeLabel
    {
        get
        {
            return ResourceManager.GetString("RoomCodeLabel", _resourceCulture);
        }
    }

    public static string RoomHostLabel
    {
        get
        {
            return ResourceManager.GetString("RoomHostLabel", _resourceCulture);
        }
    }

    public static string RoomNoPlayersLabel
    {
        get
        {
            return ResourceManager.GetString("RoomNoPlayersLabel", _resourceCulture);
        }
    }

    public static string RoomNotReadyLabel
    {
        get
        {
            return ResourceManager.GetString("RoomNotReadyLabel", _resourceCulture);
        }
    }

    public static string RoomPlayerCountFormat
    {
        get
        {
            return ResourceManager.GetString("RoomPlayerCountFormat", _resourceCulture);
        }
    }

    public static string RoomTitle
    {
        get
        {
            return ResourceManager.GetString("RoomTitle", _resourceCulture);
        }
    }

    public static string RoomWindowTitle
    {
        get
        {
            return ResourceManager.GetString("RoomWindowTitle", _resourceCulture);
        }
    }

    public static string RulesDoublesDescription
    {
        get
        {
            return ResourceManager.GetString("RulesDoublesDescription", _resourceCulture);
        }
    }

    public static string RulesDoublesTitle
    {
        get
        {
            return ResourceManager.GetString("RulesDoublesTitle", _resourceCulture);
        }
    }

    public static string RulesDrawDescription
    {
        get
        {
            return ResourceManager.GetString("RulesDrawDescription", _resourceCulture);
        }
    }

    public static string RulesDrawTitle
    {
        get
        {
            return ResourceManager.GetString("RulesDrawTitle", _resourceCulture);
        }
    }

    public static string RulesObjectiveDescription
    {
        get
        {
            return ResourceManager.GetString("RulesObjectiveDescription", _resourceCulture);
        }
    }

    public static string RulesObjectiveTitle
    {
        get
        {
            return ResourceManager.GetString("RulesObjectiveTitle", _resourceCulture);
        }
    }

    public static string RulesPreparationDescription
    {
        get
        {
            return ResourceManager.GetString("RulesPreparationDescription", _resourceCulture);
        }
    }

    public static string RulesPreparationTitle
    {
        get
        {
            return ResourceManager.GetString("RulesPreparationTitle", _resourceCulture);
        }
    }

    public static string RulesScoringDescription
    {
        get
        {
            return ResourceManager.GetString("RulesScoringDescription", _resourceCulture);
        }
    }

    public static string RulesScoringTitle
    {
        get
        {
            return ResourceManager.GetString("RulesScoringTitle", _resourceCulture);
        }
    }

    public static string RulesTurnDescription
    {
        get
        {
            return ResourceManager.GetString("RulesTurnDescription", _resourceCulture);
        }
    }

    public static string RulesTurnTitle
    {
        get
        {
            return ResourceManager.GetString("RulesTurnTitle", _resourceCulture);
        }
    }

    public static string SampleFriendOne
    {
        get
        {
            return ResourceManager.GetString("SampleFriendOne", _resourceCulture);
        }
    }

    public static string SampleFriendOneRoundOne
    {
        get
        {
            return ResourceManager.GetString("SampleFriendOneRoundOne", _resourceCulture);
        }
    }

    public static string SampleFriendOneRoundTwo
    {
        get
        {
            return ResourceManager.GetString("SampleFriendOneRoundTwo", _resourceCulture);
        }
    }

    public static string SampleFriendOneTotal
    {
        get
        {
            return ResourceManager.GetString("SampleFriendOneTotal", _resourceCulture);
        }
    }

    public static string SampleFriendThree
    {
        get
        {
            return ResourceManager.GetString("SampleFriendThree", _resourceCulture);
        }
    }

    public static string SampleFriendThreeRoundOne
    {
        get
        {
            return ResourceManager.GetString("SampleFriendThreeRoundOne", _resourceCulture);
        }
    }

    public static string SampleFriendThreeRoundTwo
    {
        get
        {
            return ResourceManager.GetString("SampleFriendThreeRoundTwo", _resourceCulture);
        }
    }

    public static string SampleFriendThreeTotal
    {
        get
        {
            return ResourceManager.GetString("SampleFriendThreeTotal", _resourceCulture);
        }
    }

    public static string SampleFriendTwo
    {
        get
        {
            return ResourceManager.GetString("SampleFriendTwo", _resourceCulture);
        }
    }

    public static string SamplePlayerCount
    {
        get
        {
            return ResourceManager.GetString("SamplePlayerCount", _resourceCulture);
        }
    }

    public static string SampleRoomCode
    {
        get
        {
            return ResourceManager.GetString("SampleRoomCode", _resourceCulture);
        }
    }

    public static string SampleWinnerLabel
    {
        get
        {
            return ResourceManager.GetString("SampleWinnerLabel", _resourceCulture);
        }
    }

    public static string SampleWinnerScore
    {
        get
        {
            return ResourceManager.GetString("SampleWinnerScore", _resourceCulture);
        }
    }

    public static string SampleYouRoundOne
    {
        get
        {
            return ResourceManager.GetString("SampleYouRoundOne", _resourceCulture);
        }
    }

    public static string SampleYouRoundTwo
    {
        get
        {
            return ResourceManager.GetString("SampleYouRoundTwo", _resourceCulture);
        }
    }

    public static string SampleYouTotal
    {
        get
        {
            return ResourceManager.GetString("SampleYouTotal", _resourceCulture);
        }
    }

    public static string SaveButtonLabel
    {
        get
        {
            return ResourceManager.GetString("SaveButtonLabel", _resourceCulture);
        }
    }

    public static string SaveProfileAccessibleName
    {
        get
        {
            return ResourceManager.GetString("SaveProfileAccessibleName", _resourceCulture);
        }
    }

    public static string ScoreConnectedPlayersFormat
    {
        get
        {
            return ResourceManager.GetString("ScoreConnectedPlayersFormat", _resourceCulture);
        }
    }

    public static string ScoreExplanation
    {
        get
        {
            return ResourceManager.GetString("ScoreExplanation", _resourceCulture);
        }
    }

    public static string ScoreNoPlayersLabel
    {
        get
        {
            return ResourceManager.GetString("ScoreNoPlayersLabel", _resourceCulture);
        }
    }

    public static string ScorePendingResultsLabel
    {
        get
        {
            return ResourceManager.GetString("ScorePendingResultsLabel", _resourceCulture);
        }
    }

    public static string ScorePlayerLabel
    {
        get
        {
            return ResourceManager.GetString("ScorePlayerLabel", _resourceCulture);
        }
    }

    public static string ScoreRoundCountFormat
    {
        get
        {
            return ResourceManager.GetString("ScoreRoundCountFormat", _resourceCulture);
        }
    }

    public static string ScoreRoundFormat
    {
        get
        {
            return ResourceManager.GetString("ScoreRoundFormat", _resourceCulture);
        }
    }

    public static string ScoreRoundOneLabel
    {
        get
        {
            return ResourceManager.GetString("ScoreRoundOneLabel", _resourceCulture);
        }
    }

    public static string ScoreRoundTwoLabel
    {
        get
        {
            return ResourceManager.GetString("ScoreRoundTwoLabel", _resourceCulture);
        }
    }

    public static string ScoreTieFormat
    {
        get
        {
            return ResourceManager.GetString("ScoreTieFormat", _resourceCulture);
        }
    }

    public static string ScoreTotalLabel
    {
        get
        {
            return ResourceManager.GetString("ScoreTotalLabel", _resourceCulture);
        }
    }

    public static string ScoreWinnerFormat
    {
        get
        {
            return ResourceManager.GetString("ScoreWinnerFormat", _resourceCulture);
        }
    }

    public static string SendCodeButtonLabel
    {
        get
        {
            return ResourceManager.GetString("SendCodeButtonLabel", _resourceCulture);
        }
    }

    public static string SettingsTitle
    {
        get
        {
            return ResourceManager.GetString("SettingsTitle", _resourceCulture);
        }
    }

    public static string SettingsWindowTitle
    {
        get
        {
            return ResourceManager.GetString("SettingsWindowTitle", _resourceCulture);
        }
    }

    public static string SetupRoomNote
    {
        get
        {
            return ResourceManager.GetString("SetupRoomNote", _resourceCulture);
        }
    }

    public static string SignUpBottonLabel
    {
        get
        {
            return ResourceManager.GetString("SignUpBottonLabel", _resourceCulture);
        }
    }

    public static string SignUpButtonAccesibleName
    {
        get
        {
            return ResourceManager.GetString("SignUpButtonAccesibleName", _resourceCulture);
        }
    }

    public static string SignUpWindowTitle
    {
        get
        {
            return ResourceManager.GetString("SignUpWindowTitle", _resourceCulture);
        }
    }

    public static string SoundEffectsVolumeLabel
    {
        get
        {
            return ResourceManager.GetString("SoundEffectsVolumeLabel", _resourceCulture);
        }
    }

    public static string SpanishLanguageAccessibleName
    {
        get
        {
            return ResourceManager.GetString("SpanishLanguageAccessibleName", _resourceCulture);
        }
    }

    public static string SpanishLanguageCode
    {
        get
        {
            return ResourceManager.GetString("SpanishLanguageCode", _resourceCulture);
        }
    }

    public static string SpanishLanguageDescription
    {
        get
        {
            return ResourceManager.GetString("SpanishLanguageDescription", _resourceCulture);
        }
    }

    public static string SpanishLanguageName
    {
        get
        {
            return ResourceManager.GetString("SpanishLanguageName", _resourceCulture);
        }
    }

    public static string StartMatchButtonLabel
    {
        get
        {
            return ResourceManager.GetString("StartMatchButtonLabel", _resourceCulture);
        }
    }

    public static string TabFriends
    {
        get
        {
            return ResourceManager.GetString("TabFriends", _resourceCulture);
        }
    }

    public static string TabRequests
    {
        get
        {
            return ResourceManager.GetString("TabRequests", _resourceCulture);
        }
    }

    public static string UpdatePasswordButtonLabel
    {
        get
        {
            return ResourceManager.GetString("UpdatePasswordButtonLabel", _resourceCulture);
        }
    }

    public static string UsernameAccessibleName
    {
        get
        {
            return ResourceManager.GetString("UsernameAccessibleName", _resourceCulture);
        }
    }

    public static string UsernameLabel
    {
        get
        {
            return ResourceManager.GetString("UsernameLabel", _resourceCulture);
        }
    }

    public static string VerificationCodeEmailBody
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeEmailBody", _resourceCulture);
        }
    }

    public static string VerificationCodeEmailSubject
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeEmailSubject", _resourceCulture);
        }
    }

    public static string VerificationCodeExpiredMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeExpiredMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeInvalidMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeInvalidMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeNotReceivedLabel
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeNotReceivedLabel", _resourceCulture);
        }
    }

    public static string VerificationCodeResendLabel
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeResendLabel", _resourceCulture);
        }
    }

    public static string VerificationCodeResendWaitMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeResendWaitMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeResentMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeResentMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeSendErrorMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeSendErrorMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeSentMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeSentMessage", _resourceCulture);
        }
    }

    public static string VerificationCodeTooManyAttemptsMessage
    {
        get
        {
            return ResourceManager.GetString("VerificationCodeTooManyAttemptsMessage", _resourceCulture);
        }
    }

    public static string VerificationTitle
    {
        get
        {
            return ResourceManager.GetString("VerificationTitle", _resourceCulture);
        }
    }

    public static string ViewScoresButtonLabel
    {
        get
        {
            return ResourceManager.GetString("ViewScoresButtonLabel", _resourceCulture);
        }
    }

    public static string VolumePercentageFormat
    {
        get
        {
            return ResourceManager.GetString("VolumePercentageFormat", _resourceCulture);
        }
    }

    public static string WaitingRoomDescription
    {
        get
        {
            return ResourceManager.GetString("WaitingRoomDescription", _resourceCulture);
        }
    }

    public static string WaitingRoomTitle
    {
        get
        {
            return ResourceManager.GetString("WaitingRoomTitle", _resourceCulture);
        }
    }

    public static string WaitingRoomWindowTitle
    {
        get
        {
            return ResourceManager.GetString("WaitingRoomWindowTitle", _resourceCulture);
        }
    }

    public static string WinsLabel
    {
        get
        {
            return ResourceManager.GetString("WinsLabel", _resourceCulture);
        }
    }

    public static string YouHostLabel
    {
        get
        {
            return ResourceManager.GetString("YouHostLabel", _resourceCulture);
        }
    }

    public static string YouPlayerLabel
    {
        get
        {
            return ResourceManager.GetString("YouPlayerLabel", _resourceCulture);
        }
    }
}
