//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DominoTrainGame.Shared.Resources.Localization.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string AddButtonLabel {
            get {
                return ResourceManager.GetString("AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta?.
        /// </summary>
        public static string AlreadyHaveAccountLabel {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / Audio.
        /// </summary>
        public static string AudioSectionLabel {
            get {
                return ResourceManager.GetString("AudioSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string AvatarSectionLabel {
            get {
                return ResourceManager.GetString("AvatarSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografía.
        /// </summary>
        public static string BiographyLabel {
            get {
                return ResourceManager.GetString("BiographyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar nueva contraseña.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string CreateGameTitle {
            get {
                return ResourceManager.GetString("CreateGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/ Credenciales.
        /// </summary>
        public static string CredentialSectionLabel {
            get {
                return ResourceManager.GetString("CredentialSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al conectarse.
        /// </summary>
        public static string DatabaseErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entiendo que esta acción no se puede deshacer..
        /// </summary>
        public static string DeleteAccountConfirmationLabel {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma que deseas eliminar tu cuenta..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu contraseña para confirmar tu identidad..
        /// </summary>
        public static string DeleteAccountPasswordHint {
            get {
                return ResourceManager.GetString("DeleteAccountPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar cuenta.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una vez eliminada, no podrás recuperar tu cuenta..
        /// </summary>
        public static string DeleteAccountWarningDescription {
            get {
                return ResourceManager.GetString("DeleteAccountWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción permanente.
        /// </summary>
        public static string DeleteAccountWarningTitle {
            get {
                return ResourceManager.GetString("DeleteAccountWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditButtonLabel {
            get {
                return ResourceManager.GetString("EditButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string EmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico o usuario.
        /// </summary>
        public static string EmailOrUsernameLabel {
            get {
                return ResourceManager.GetString("EmailOrUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string EnglishLanguageDescription {
            get {
                return ResourceManager.GetString("EnglishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguageName {
            get {
                return ResourceManager.GetString("EnglishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir al menú.
        /// </summary>
        public static string ExitToMenuButtonLabel {
            get {
                return ResourceManager.GetString("ExitToMenuButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPasswordLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string FriendsLabel {
            get {
                return ResourceManager.GetString("FriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas del juego.
        /// </summary>
        public static string GameRulesTitle {
            get {
                return ResourceManager.GetString("GameRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas jugadas.
        /// </summary>
        public static string GamesPlayedLabel {
            get {
                return ResourceManager.GetString("GamesPlayedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domino Train.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        public static string GuestButtonLabel {
            get {
                return ResourceManager.GetString("GuestButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico no es válido..
        /// </summary>
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La contraseña debe tener al menos {0} caracteres.
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrarás el código en la pantalla de configuración de la partida..
        /// </summary>
        public static string InvitationCodeHint {
            get {
                return ResourceManager.GetString("InvitationCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce el código que te compartió el anfitrión de la partida..
        /// </summary>
        public static string InvitationDescription {
            get {
                return ResourceManager.GetString("InvitationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de invitación.
        /// </summary>
        public static string InvitationTitle {
            get {
                return ResourceManager.GetString("InvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una invitación? Introduce el código y toma tu lugar en la sala..
        /// </summary>
        public static string JoinGameDescription {
            get {
                return ResourceManager.GetString("JoinGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse a partida.
        /// </summary>
        public static string JoinGameTitle {
            get {
                return ResourceManager.GetString("JoinGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar a la sala.
        /// </summary>
        public static string JoinRoomButtonLabel {
            get {
                return ResourceManager.GetString("JoinRoomButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu lugar
        ///en el tren.
        /// </summary>
        public static string JoinSidebarTitle {
            get {
                return ResourceManager.GetString("JoinSidebarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Únete a la mesa.
        /// </summary>
        public static string JoinTableTitle {
            get {
                return ResourceManager.GetString("JoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 / Idioma.
        /// </summary>
        public static string LanguageSectionLabel {
            get {
                return ResourceManager.GetString("LanguageSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay puntuaciones de partidas terminadas.
        /// </summary>
        public static string LeaderboardEmptyMessage {
            get {
                return ResourceManager.GetString("LeaderboardEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación por victorias en partidas terminadas..
        /// </summary>
        public static string LeaderboardExplanation {
            get {
                return ResourceManager.GetString("LeaderboardExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por jugador.
        /// </summary>
        public static string LeaderboardFilterLabel {
            get {
                return ResourceManager.GetString("LeaderboardFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron cargar las puntuaciones. Revisa la conexión e inténtalo de nuevo.
        /// </summary>
        public static string LeaderboardLoadErrorMessage {
            get {
                return ResourceManager.GetString("LeaderboardLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando puntuaciones….
        /// </summary>
        public static string LeaderboardLoadingMessage {
            get {
                return ResourceManager.GetString("LeaderboardLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay jugadores que coincidan con el filtro.
        /// </summary>
        public static string LeaderboardNoMatchesMessage {
            get {
                return ResourceManager.GetString("LeaderboardNoMatchesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla de posiciones.
        /// </summary>
        public static string LeaderboardTitle {
            get {
                return ResourceManager.GetString("LeaderboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión para continuar tu partida.
        /// </summary>
        public static string LoginSidebarDescription {
            get {
                return ResourceManager.GetString("LoginSidebarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string LogOutButtonLabel {
            get {
                return ResourceManager.GetString("LogOutButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar listo.
        /// </summary>
        public static string MarkReadyButtonLabel {
            get {
                return ResourceManager.GetString("MarkReadyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos por ronda y total acumulado..
        /// </summary>
        public static string MatchResultsDescription {
            get {
                return ResourceManager.GetString("MatchResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntajes y resultados.
        /// </summary>
        public static string MatchResultsTitle {
            get {
                return ResourceManager.GetString("MatchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El doble máximo define el conjunto de fichas de la partida..
        /// </summary>
        public static string MaximumDoubleDescription {
            get {
                return ResourceManager.GetString("MaximumDoubleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble máximo.
        /// </summary>
        public static string MaximumDoubleLabel {
            get {
                return ResourceManager.GetString("MaximumDoubleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado por el anfitrión..
        /// </summary>
        public static string MaximumDoubleReadOnlyDescription {
            get {
                return ResourceManager.GetString("MaximumDoubleReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembro desde.
        /// </summary>
        public static string MemberSinceLabel {
            get {
                return ResourceManager.GetString("MemberSinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string MessageIncorrectPassword {
            get {
                return ResourceManager.GetString("MessageIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario o correo ya está registrado.
        /// </summary>
        public static string MessageUserAlreadyExists {
            get {
                return ResourceManager.GetString("MessageUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string MessageUserNotFound {
            get {
                return ResourceManager.GetString("MessageUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Música.
        /// </summary>
        public static string MusicVolumeLabel {
            get {
                return ResourceManager.GetString("MusicVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige cómo quieres comenzar tu próximo viaje..
        /// </summary>
        public static string NewGameDescription {
            get {
                return ResourceManager.GetString("NewGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva partida.
        /// </summary>
        public static string NewGameTitle {
            get {
                return ResourceManager.GetString("NewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ Nuevo pasajero.
        /// </summary>
        public static string NewPassengerSubtitle {
            get {
                return ResourceManager.GetString("NewPassengerSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una contraseña diferente a la actual y confírmala..
        /// </summary>
        public static string NewPasswordHint {
            get {
                return ResourceManager.GetString("NewPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente ronda.
        /// </summary>
        public static string NextRoundButtonLabel {
            get {
                return ResourceManager.GetString("NextRoundButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        public static string NoAccountLabel {
            get {
                return ResourceManager.GetString("NoAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compartas tu contraseña con otros jugadores..
        /// </summary>
        public static string PasswordPrivacyNote {
            get {
                return ResourceManager.GetString("PasswordPrivacyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordsDoNotMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar.
        /// </summary>
        public static string PlayButtonLabel {
            get {
                return ResourceManager.GetString("PlayButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador.
        /// </summary>
        public static string PlayerLabel {
            get {
                return ResourceManager.GetString("PlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        public static string RankLabel {
            get {
                return ResourceManager.GetString("RankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string ReadyStatusLabel {
            get {
                return ResourceManager.GetString("ReadyStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu contraseña se actualizó correctamente.
        /// </summary>
        public static string RecoverPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("RecoverPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        public static string RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string RefreshButtonLabel {
            get {
                return ResourceManager.GetString("RefreshButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma asiento y regístrate para comenzar tu partida.
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro completado correctamente..
        /// </summary>
        public static string RegistrationSuccessMessage {
            get {
                return ResourceManager.GetString("RegistrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string RemoveButtonLabel {
            get {
                return ResourceManager.GetString("RemoveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes.
        /// </summary>
        public static string RequestsLabel {
            get {
                return ResourceManager.GetString("RequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos son obligatorios..
        /// </summary>
        public static string RequiredFieldsMessage {
            get {
                return ResourceManager.GetString("RequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparte este código con tus amigos..
        /// </summary>
        public static string RoomCodeDescription {
            get {
                return ResourceManager.GetString("RoomCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de la sala.
        /// </summary>
        public static string RoomCodeLabel {
            get {
                return ResourceManager.GetString("RoomCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfitrión.
        /// </summary>
        public static string RoomHostLabel {
            get {
                return ResourceManager.GetString("RoomHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay jugadores en la sala..
        /// </summary>
        public static string RoomNoPlayersLabel {
            get {
                return ResourceManager.GetString("RoomNoPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listo.
        /// </summary>
        public static string RoomNotReadyLabel {
            get {
                return ResourceManager.GetString("RoomNotReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string RoomPlayerCountFormat {
            get {
                return ResourceManager.GetString("RoomPlayerCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de partida.
        /// </summary>
        public static string RoomTitle {
            get {
                return ResourceManager.GetString("RoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Después de colocar un doble, juega otra ficha. Un doble pendiente debe cubrirse antes de continuar en otros trenes..
        /// </summary>
        public static string RulesDoublesDescription {
            get {
                return ResourceManager.GetString("RulesDoublesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05 / Fichas dobles.
        /// </summary>
        public static string RulesDoublesTitle {
            get {
                return ResourceManager.GetString("RulesDoublesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no puedes jugar, roba una ficha. Si tampoco puedes colocarla, pasa y deja tu tren abierto a los demás..
        /// </summary>
        public static string RulesDrawDescription {
            get {
                return ResourceManager.GetString("RulesDrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04 / Robar y pasar.
        /// </summary>
        public static string RulesDrawTitle {
            get {
                return ResourceManager.GetString("RulesDrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloca tus fichas y termina con la menor cantidad de puntos. Al final de la partida, gana el menor total..
        /// </summary>
        public static string RulesObjectiveDescription {
            get {
                return ResourceManager.GetString("RulesObjectiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 / Objetivo.
        /// </summary>
        public static string RulesObjectiveTitle {
            get {
                return ResourceManager.GetString("RulesObjectiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El doble inicial se coloca en el centro. Cada jugador tiene un tren y las fichas restantes forman el pozo..
        /// </summary>
        public static string RulesPreparationDescription {
            get {
                return ResourceManager.GetString("RulesPreparationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 / Preparación.
        /// </summary>
        public static string RulesPreparationTitle {
            get {
                return ResourceManager.GetString("RulesPreparationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ronda termina al agotarse una mano o bloquearse la mesa. Suma los puntos de tus fichas restantes a tu total..
        /// </summary>
        public static string RulesScoringDescription {
            get {
                return ResourceManager.GetString("RulesScoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06 / Fin de la ronda.
        /// </summary>
        public static string RulesScoringTitle {
            get {
                return ResourceManager.GetString("RulesScoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une una ficha por un extremo del mismo valor. Puedes jugar en tu tren, en el tren mexicano o en un tren abierto..
        /// </summary>
        public static string RulesTurnDescription {
            get {
                return ResourceManager.GetString("RulesTurnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 / En tu turno.
        /// </summary>
        public static string RulesTurnTitle {
            get {
                return ResourceManager.GetString("RulesTurnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores conectados: {0}.
        /// </summary>
        public static string ScoreConnectedPlayersFormat {
            get {
                return ResourceManager.GetString("ScoreConnectedPlayersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menos puntos, mejor resultado..
        /// </summary>
        public static string ScoreExplanation {
            get {
                return ResourceManager.GetString("ScoreExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no hay jugadores ni resultados que mostrar..
        /// </summary>
        public static string ScoreNoPlayersLabel {
            get {
                return ResourceManager.GetString("ScoreNoPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados pendientes.
        /// </summary>
        public static string ScorePendingResultsLabel {
            get {
                return ResourceManager.GetString("ScorePendingResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rondas: {0}.
        /// </summary>
        public static string ScoreRoundCountFormat {
            get {
                return ResourceManager.GetString("ScoreRoundCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ronda {0}.
        /// </summary>
        public static string ScoreRoundFormat {
            get {
                return ResourceManager.GetString("ScoreRoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empate: {0}.
        /// </summary>
        public static string ScoreTieFormat {
            get {
                return ResourceManager.GetString("ScoreTieFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ScoreTotalLabel {
            get {
                return ResourceManager.GetString("ScoreTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganador: {0}.
        /// </summary>
        public static string ScoreWinnerFormat {
            get {
                return ResourceManager.GetString("ScoreWinnerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string SendCodeButtonLabel {
            get {
                return ResourceManager.GetString("SendCodeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string SignUpButtonLabel {
            get {
                return ResourceManager.GetString("SignUpButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectos de sonido.
        /// </summary>
        public static string SoundEffectsVolumeLabel {
            get {
                return ResourceManager.GetString("SoundEffectsVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SpanishLanguageDescription {
            get {
                return ResourceManager.GetString("SpanishLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string SpanishLanguageName {
            get {
                return ResourceManager.GetString("SpanishLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string StartMatchButtonLabel {
            get {
                return ResourceManager.GetString("StartMatchButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadísticas.
        /// </summary>
        public static string StatisticsLabel {
            get {
                return ResourceManager.GetString("StatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu código de verificación de Domino Train es: {0}. Vence en {1} minutos. Si no solicitaste este registro, ignora este mensaje.
        /// </summary>
        public static string VerificationCodeEmailBody {
            get {
                return ResourceManager.GetString("VerificationCodeEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu código de verificación.
        /// </summary>
        public static string VerificationCodeEmailSubject {
            get {
                return ResourceManager.GetString("VerificationCodeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código venció.
        /// </summary>
        public static string VerificationCodeExpiredMessage {
            get {
                return ResourceManager.GetString("VerificationCodeExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código es incorrecto. Inténtalo de nuevo.
        /// </summary>
        public static string VerificationCodeInvalidMessage {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenviar código.
        /// </summary>
        public static string VerificationCodeResendLabel {
            get {
                return ResourceManager.GetString("VerificationCodeResendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera {0} segundos para pedir otro código..
        /// </summary>
        public static string VerificationCodeResendWaitMessage {
            get {
                return ResourceManager.GetString("VerificationCodeResendWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviamos un código nuevo. El anterior ya no es válido..
        /// </summary>
        public static string VerificationCodeResentMessage {
            get {
                return ResourceManager.GetString("VerificationCodeResentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo enviar el correo de verificación. Revisa tu dirección e inténtalo de nuevo..
        /// </summary>
        public static string VerificationCodeSendErrorMessage {
            get {
                return ResourceManager.GetString("VerificationCodeSendErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviamos un código de 6 dígitos a {0}. Escríbelo para completar tu registro..
        /// </summary>
        public static string VerificationCodeSentMessage {
            get {
                return ResourceManager.GetString("VerificationCodeSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demasiados intentos fallidos.
        /// </summary>
        public static string VerificationCodeTooManyAttemptsMessage {
            get {
                return ResourceManager.GetString("VerificationCodeTooManyAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código.
        /// </summary>
        public static string VerificationTitle {
            get {
                return ResourceManager.GetString("VerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar.
        /// </summary>
        public static string VerifyButtonLabel {
            get {
                return ResourceManager.GetString("VerifyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}%.
        /// </summary>
        public static string VolumePercentageFormat {
            get {
                return ResourceManager.GetString("VolumePercentageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido de vuelta.
        /// </summary>
        public static string WelcomeBackTitle {
            get {
                return ResourceManager.GetString("WelcomeBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} · {1}.
        /// </summary>
        public static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victorias.
        /// </summary>
        public static string WinsLabel {
            get {
                return ResourceManager.GetString("WinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú.
        /// </summary>
        public static string YouPlayerLabel {
            get {
                return ResourceManager.GetString("YouPlayerLabel", resourceCulture);
            }
        }
    }
}
