//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bans
    {
        public int BanId { get; set; }
        public int PlayerId { get; set; }
        public string Reason { get; set; }
        public string BanType { get; set; }
        public System.DateTime StartedAt { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
