//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendshipRequests
    {
        public int FriendshipRequestsID { get; set; }
        public int RequesterPlayerId { get; set; }
        public int AddresseePlayerId { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime RequestedAt { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual StatusFriendshipRequests StatusFriendshipRequests { get; set; }
    }
}
