//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendshipRequest
    {
        public int FriendshipRequestsID { get; set; }
        public int RequesterPlayerId { get; set; }
        public int AddresseePlayerId { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime RequestedAt { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual StatusFriendshipRequest StatusFriendshipRequest { get; set; }
    }
}
