//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LobbyPlayers
    {
        public int PlayerId { get; set; }
        public int LobbyId { get; set; }
        public byte IsReady { get; set; }
    
        public virtual Lobbies Lobbies { get; set; }
        public virtual Players Players { get; set; }
    }
}
