//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominoTrainGame
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DominoGameDBEntities : DbContext
    {
        public DominoGameDBEntities()
            : base("name=DominoGameDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bans> Bans { get; set; }
        public virtual DbSet<FriendshipRequests> FriendshipRequests { get; set; }
        public virtual DbSet<Lobbies> Lobbies { get; set; }
        public virtual DbSet<LobbyPlayers> LobbyPlayers { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<MatchResults> MatchResults { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<StatusFriendshipRequests> StatusFriendshipRequests { get; set; }
    }
}
