param(
    [Parameter(Mandatory = $true)]
    [string] $ProjectDirectory
)

$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath($ProjectDirectory)
[xml] $project = [IO.File]::ReadAllText((Join-Path $projectRoot 'DominoTrainGame.csproj'))
$utf8 = New-Object System.Text.UTF8Encoding($false)
$header = "// <auto-generated>`n// Generated code. The build normalizes this file after regeneration.`n" +
    "// </auto-generated>`n"

foreach ($item in $project.Project.ItemGroup.Compile)
{
    if ($item.AutoGen -ne 'True' -and $item.DependentUpon -notlike '*.tt')
    {
        continue
    }

    $path = [IO.Path]::GetFullPath((Join-Path $projectRoot $item.Include))
    if (-not $path.StartsWith($projectRoot + [IO.Path]::DirectorySeparatorChar))
    {
        throw "Generated source is outside the project: $path"
    }

    $original = [IO.File]::ReadAllText($path)
    $source = $original.Replace("`r`n", "`n")
    $namespaceMatch = [regex]::Match($source, '(?m)^namespace\s+([\w.]+)\s*([;{])')
    if (-not $namespaceMatch.Success)
    {
        $emptySource = [regex]::Replace($source, '(?m)^\s*(//[^\n]*|using [\w.]+;)\s*\n?', '')
        if (-not $emptySource.Trim())
        {
            $result = $header.Replace("`n", "`r`n")
            if ($result -cne $original)
            {
                [IO.File]::WriteAllText($path, $result, $utf8)
            }
        }

        continue
    }

    $namespace = $namespaceMatch.Groups[1].Value
    $usings = @([regex]::Matches($source, '(?m)^\s*using ([\w.]+);') |
        ForEach-Object { $_.Groups[1].Value })
    $isBlockNamespace = $namespaceMatch.Groups[2].Value -eq '{'
    $source = $source.Substring($namespaceMatch.Index + $namespaceMatch.Length).Trim()
    if ($isBlockNamespace)
    {
        $source = [regex]::Replace($source, '\s*}\s*$', '')
        $source = [regex]::Replace($source, '(?m)^    ', '')
    }

    $source = [regex]::Replace($source, '(?m)^\s*using [\w.]+;\s*\n?', '')
    $source = [regex]::Replace($source, '(?m)^\s*///.*\n?', '')
    $source = [regex]::Replace($source, '(?m)^\s*//.*\n?', '')
    $source = [regex]::Replace($source, '\bresourceMan\b', '_resourceManager')
    $source = [regex]::Replace($source, '\bresourceCulture\b', '_resourceCulture')
    $source = [regex]::Replace($source, '\bdefaultInstance\b', '_defaultInstance')
    if ($source -cmatch '(?<![\w.])Nullable\s*<')
    {
        $usings += 'System'
    }
    if ($source -cmatch '(?<![\w.])(ICollection|HashSet)\s*<')
    {
        $usings += 'System.Collections.Generic'
    }
    if ($source -cmatch ': DbContext\b')
    {
        $usings += 'System.Data.Entity'
        $usings += 'System.Data.Entity.Infrastructure'
    }

    # Remove imports that the generated files replace with fully qualified type names.
    $usings = @($usings | Where-Object {
        ($_ -ne 'System' -or $source -cmatch '(?<![\w.])(Nullable|DateTime|Guid|String|Object|EventArgs)\b') -and
        ($_ -ne 'System.Collections.Generic' -or $source -cmatch '(?<![\w.])(ICollection|HashSet|List)\s*<')
    } | Sort-Object -Unique)

    # Resource designers emit opening braces on the same line as types and accessors.
    $bracePattern = '(?m)^(?<indent> *)' +
        '(?<declaration>(?:public|internal|private|protected|if|else|get|set)\b[^\n{]*?) *{ *$'
    $source = [regex]::Replace($source, $bracePattern, {
        param($match)
        $match.Groups['indent'].Value + $match.Groups['declaration'].Value.TrimEnd() + "`n" +
            $match.Groups['indent'].Value + '{'
    })

    $managerPattern = '(?m)^(?<indent> *)' +
        '(?<prefix>global::System.Resources.ResourceManager \w+ = new ' +
        'global::System.Resources.ResourceManager)\((?<name>"[^"]+"), (?<assembly>typeof\(\w+\).Assembly)\);'
    $source = [regex]::Replace($source, $managerPattern, {
        param($match)
        $indent = $match.Groups['indent'].Value
        $indent + $match.Groups['prefix'].Value + "(`n" +
            $indent + '    ' + $match.Groups['name'].Value + ",`n" +
            $indent + '    ' + $match.Groups['assembly'].Value + "`n" + $indent + ');'
    })

    $source = [regex]::Replace($source, '(?m)^(?<indent> *)(?<attribute>\[[\w:.]+)\((?<args>[^\n]+)\)\]$', {
        param($match)
        if ($match.Value.Length -le 120)
        {
            return $match.Value
        }

        $indent = $match.Groups['indent'].Value
        $arguments = [regex]::Split($match.Groups['args'].Value, ', (?=(?:[^"]*"[^"]*")*[^"]*$)')
        $indent + $match.Groups['attribute'].Value + "(`n" +
            $indent + '    ' + ($arguments -join (",`n" + $indent + '    ')) + "`n" + $indent + ')]'
    })

    $settingsPattern = '(?m)^(?<prefix>    private static Settings _defaultInstance =) (?<value>.*);$'
    $source = [regex]::Replace($source, $settingsPattern, {
        param($match)
        $match.Groups['prefix'].Value + "`n        " + $match.Groups['value'].Value + ';'
    })

    # Keep generated context properties before protected methods.
    $methodPattern = '(?ms)^    protected override void OnModelCreating\(DbModelBuilder modelBuilder\)\n' +
        '    {\n.*?^    }\n?'
    $modelMethod = [regex]::Match($source, $methodPattern)
    if ($modelMethod.Success)
    {
        $source = [regex]::Replace($source, $methodPattern, '')
        $lastBrace = $source.LastIndexOf('}')
        $source = $source.Substring(0, $lastBrace).TrimEnd() + "`n`n" +
            $modelMethod.Value.TrimEnd() + "`n" + $source.Substring($lastBrace)
    }

    $source = [regex]::Replace($source, '(?m)(^    private [^\n]+;\n)(?=    public)', '$1' + "`n")
    $source = [regex]::Replace($source, '(?m)(^    }\n)(?=    public)', '$1' + "`n")
    $source = [regex]::Replace($source, '\n[ \t]*\n(?:[ \t]*\n)+', "`n`n")
    $source = [regex]::Replace($source, '(?m)[ \t]+$', '').Trim()
    $usingBlock = (@($usings | ForEach-Object { "using $_;" }) -join "`n")
    if ($usingBlock)
    {
        $usingBlock += "`n`n"
    }

    $result = ($header + "`n" + $usingBlock + "namespace $namespace;`n`n" + $source + "`n").Replace("`n", "`r`n")
    if ($result -cne $original)
    {
        [IO.File]::WriteAllText($path, $result, $utf8)
    }
}
