// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame.Properties;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
    "System.Resources.Tools.StronglyTypedResourceBuilder",
    "4.0.0.0"
)]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources
{
    private static global::System.Resources.ResourceManager _resourceManager;
    private static global::System.Globalization.CultureInfo _resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        "Microsoft.Performance",
        "CA1811:AvoidUncalledPrivateCode"
    )]
    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced
    )]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if ((_resourceManager == null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                    "DominoTrainGame.Properties.Resources",
                    typeof(Resources).Assembly
                );
                _resourceManager = temp;
            }

            return _resourceManager;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced
    )]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return _resourceCulture;
        }

        set
        {
            _resourceCulture = value;
        }
    }
}
