// <auto-generated>
// Generated code. The build normalizes this file after regeneration.
// </auto-generated>

namespace DominoTrainGame.Properties;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
    "Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator",
    "11.0.0.0"
)]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static Settings _defaultInstance =
        ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

    public static Settings Default
    {
        get
        {
            return _defaultInstance;
        }
    }
}
